### ISSUE TITLE
deceaseddelta displaying negative value

### ISSUE THREAD

**Issue by nirajwagh** [covid19india/api#10]
Hello,
The API response for https://api.covid19india.org/data.json is displaying a negative value for "key_values ->deceaseddelta".
Is this correct? Key_values object displays today's cases, right?
Thanks for the API and data.

![negative](https://user-images.githubusercontent.com/35917455/77611558-a33aee00-6f4b-11ea-9c75-898230211519.png)

**Comment by JunaidBabu** [comment]
Thanks for the report. There was a mistake in the entry yesterday. This has been corrected and pushed.
