### ISSUE TITLE
Data value mismatch

### ISSUE THREAD

**Issue by ninjakx** [covid19india/api#103]
**[stateDailyResponse.data.states_daily](https://api.covid19india.org/states_daily.json):**
```
an: "0"
ap: "1"
ar: "0"
as: "0"
br: "0"
ch: "0"
ct: "0"
date: "14-Mar-20"
dd: "0"
dl: "7"
dn: "0"
ga: "0"
gj: "0"
hp: "0"
hr: "14"
jh: "0"
jk: "0"
ka: "6"
kl: "19"
la: "0"
ld: "0"
mh: "14"
ml: "0"
mn: "0"
mp: "0"
mz: "0"
nl: "0"
or: "0"
pb: "1"
py: "0"
rj: "3"
sk: "0"
status: "Confirmed"
tg: "1"
tn: "1"
tr: "0"
tt: "79"
up: "12"
ut: "0"
wb: "0"
```
This sum up to 158

**[response.data.cases_time_series](https://api.covid19india.org/data.json):**
confirmed cases was for 14th march: 
102

**Comment by sudevschiz** [comment]
Data on 14th March would have a mismatch because we started collecting data from that point on.  So you can think of the data on 14th March to be "as of 14th March".

If volunteers get some time and this becomes critical for some analysis, we will try to back-udpate this data. Thanks for reporting.
