### ISSUE TITLE
raw data mismatch with state wise data

### ISSUE THREAD

**Issue by aritrapra** [covid19india/api#106]
recovered and death cases count mismatch with state wise data.

**Comment by sudevschiz** [comment]
Please don't use the Status column in Raw_Data. We are not able to match exact patient to their recovery or demise now.

**Comment by aritrapra** [comment]
Instead of raw data I used both  recovery and death data and raw data to calculate but the return result is same. The decreased colomn of recovary and death data is also didnt get the correct calculation.
