### ISSUE TITLE
Testing data availability

### ISSUE THREAD

**Issue by farhan-ejaz** [covid19india/api#109]
- API which can give date wise testing data (number of tests done) state-wise and district wise

- API which can give the consolidated number of tests done state-wise and district wise

This can be used to evaluate the relationship between the tests done and the cases detected.

**Comment by sudevschiz** [comment]
It's already available here : https://api.covid19india.org/data.json

Please checkout the "tested" key. Thank you.

![image](https://user-images.githubusercontent.com/4298868/79249239-ef78ae80-7eb7-11ea-9723-a1d4c0d409f3.png)

**Comment by Zaraki596** [comment]
> It's already available here : https://api.covid19india.org/data.json
> 
> Please checkout the "tested" key. Thank you.
> 
> ![image](https://user-images.githubusercontent.com/4298868/79249239-ef78ae80-7eb7-11ea-9723-a1d4c0d409f3.png)

How can we figure out form this which state tested data it has?
