### ISSUE TITLE
Create a workflow to organize and store snapshot of the data as CSV file once a day

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/api#116]
- This will help in keeping a backup of the files
- Also helps analysts to directly download files as csv in case they don't want to parse through an API

TODO:

1. Fetch and convert all the data as CSV
2. Identify a nice folder structure.
3. Setup a separate GitHub workflow to run at around 03AM IST.

**Comment by karanehra** [comment]
I would love to help you with this if help is still required.
