### ISSUE TITLE
currentstatus of patients not updated in raw data API

### ISSUE THREAD

**Issue by faisalchishtii** [covid19india/api#120]
https://api.covid19india.org/raw_data.json

When we count the number of patients Hospitalized/Recovered/Deceased using raw data api `currentstatus`, we get:

**12169** patients marked as `Hospitalized`

**167** patients marked as `Recovered`

**39** patients marked as `Deceased`

while the actual count is:

![image](https://user-images.githubusercontent.com/26409919/79385970-0f2ad800-7f87-11ea-9aec-2e1342a0fc0e.png)

**Comment by sudevschiz** [comment]
Please don't use the Current Status of the patient in the `raw_data.json` endpoint. We simply don't have the information whether the exact patient has recovered or deceased anymore.

This field will soon be deprecated.

**Comment by faisalchishtii** [comment]
@sudevschiz Is there an alternate way to calculate statewise confirmed/active/deceased/recovered patients?
