### ISSUE TITLE
Okay. Why is the DATA NOT AN ARRAY! 

### ISSUE THREAD

**Issue by cell91** [covid19india/api#134]
Please restructer it for Arrays. Would be much easier to parse.
The District wise JSON file.

**Comment by cibinjoseph** [comment]
Have you taken a look at the version 2 api for state-district-wise api?  
The data is arranged as an array in it.

Link: [state_district_wise v2](https://api.covid19india.org/v2/state_district_wise.json)

**Comment by cell91** [comment]
Yeah sorry , checked it later, sorry
