### ISSUE TITLE
States were sorted earlier with respect to confirmed cases, now they are not.

### ISSUE THREAD

**Issue by gurrrung** [covid19india/api#135]
This is the order fetched from API
![Screenshot from 2020-04-18 12-13-40](https://user-images.githubusercontent.com/30543444/79630347-19f39180-816e-11ea-800a-3b64fa943dc6.png)

**Comment by osamabari** [comment]
Please assign it it me, I will work on it

**Comment by sudevschiz** [comment]
@gurrrung It's advisable to handle such things at the api consumer end. Please do capture the information and sort it according to your use. 
@osamabari , the API is just a bridge between the sheets and github. Let's not try to add too much processing while the data is fetched. Consumers of the API can handle such sorting issues. Thanks for your interest!
