### ISSUE TITLE
data.json -> case_time_series is not updated

### ISSUE THREAD

**Issue by 98farhan94** [covid19india/api#139]
The case_time_series has not updated since yesterday. Until yesterday, it was refreshing in real-time. What is the expected behaviour for case_time_series? I am using case_time_series from data.json and states_daily.json - both of them have not updated today.

Is statewise the way to go to keep data up to date?

**Comment by sudevschiz** [comment]
Cases Time series and State_daily will get updated for the same day around 11:30PM. So, if you need the tentative numbers for the day, you need to add up the cases in Statewise json

**Comment by 98farhan94** [comment]
Got it, thanks.
