### ISSUE TITLE
Feature Request : Containment Zone information across India and State wise

### ISSUE THREAD

**Issue by ApoorvSaxena** [covid19india/api#143]

**Comment by sudevschiz** [comment]
Do you have a datasource for this?

**Comment by KMaheshBhat** [comment]
I did not realize there were different projects for UI and Datasource. 

Source: https://www.news18.com/news/india/standalone-shops-including-those-selling-liquor-to-be-allowed-in-orange-green-zones-sources-2601535.html

Attached TXT is district-wise zones in CSV format : [20200501-india-covid-zones.txt](https://github.com/covid19india/api/files/4564660/20200501-india-covid-zones.txt)

**Comment by JunaidBabu** [comment]
http://api.covid19india.org/zones.json

**Comment by kanaujiasachin** [comment]
What is the frequency of updates for the Zones data?
