### ISSUE TITLE
V2: State_district_wise.json -> Maharashtra has "district": "Other States*"

### ISSUE THREAD

**Issue by 98farhan94** [covid19india/api#148]
The output already has a district "Unknown" for awaited results. The district titled "Other States*" seems to be a bug or perhaps is for something that's not documented. If so, please clarify the difference between Unknown and Other States.

**Comment by bee-rickey** [comment]
This is inline with how states are reporting the cases. Unknown are when districts aren't mapped. Other states are when states categorize patients from other states.
