### ISSUE TITLE
Deaths reported as 0

### ISSUE THREAD

**Issue by aravindnc** [covid19india/api#15]
https://api.covid19india.org/state_district_wise.json

District wise death is showing as 0 for all states and districts.

**Comment by zaxwebs** [comment]
Hi, had a look. The **deaths are being reported correctly**.
Examples: South West Delhi, Madurai, Kalaburagi, etc.

Currently, only 13 of 137 districts have deaths.

**Comment by sudevschiz** [comment]
This is more more about the data itself. Would be good to report in the group.

**Comment by aravindnc** [comment]
No. When I checked before all district in Kerala were reported 0 deaths. But I haven't checked now.
