### ISSUE TITLE
All APIs not returning data from 20th April onwards

### ISSUE THREAD

**Issue by vikkyomkar** [covid19india/api#151]
All APIs not returning data from 20th April onwards.
Was anything changed?

**Comment by pushppriya** [comment]
Yeah.. I also observed the same behaviour for https://api.covid19india.org/raw_data.json and https://api.covid19india.org/data.json end points. I could not find updated data in google sheets as well. 
Is there any running issue?

**Comment by vasanianil** [comment]
same here, can not see new data

**Comment by JunaidBabu** [comment]
raw_data.json is currently not updated. We are working on a fix. data.json should be having the latest info. could you check again?

**Comment by JunaidBabu** [comment]
Resolved
