### ISSUE TITLE
Use Airtable instead of sheets

### ISSUE THREAD

**Issue by pbteja1998** [covid19india/api#152]
Have you explored the option to use airtable as database instead of Google Sheets?

**Comment by bee-rickey** [comment]
Hi, is there any specific advantage that we achieve by migrating to Airtable?

**Comment by pbteja1998** [comment]
@bee-rickey There are many advantages of migrating to Airtable. I will list some of these

- It's visually appealing and easy to use
- You can link between different tables and records
- You can have different views of the same table with different filters/sort criteria, different visible fields. 
- You can create a form view which can add the records directly to table after filling it up and submitting it(similar to google forms) 
- You can have different data types - single line text, long text, date, phone number, email, url, barcode, number, currency, percent, duration, auto increment number, attachment, single select, multiple select, foreign key to different table, created time, duration etc 
- You can have computed fields which can be autocomputed based on formulas
- You can do CRUD operations on the table with a ready api provided by airtable, and a custom documentation will be automatically generated just for the base that you create. 
- They also have a easy to use Javascript client, if for some reason we don't to use their api
- Different access levels can be set for different users - Owner, Creator, Editor, Commentor, Readonly
- You also get revision history and snapshot history 
- There are also web, desktop, Android and ios apps

Airtable took the best things out of both spreadsheets and databases and put it into one.

**Comment by pbteja1998** [comment]
There is also a limit of 50,000 records/base

**Comment by bee-rickey** [comment]
And what's the effort for migration of data? Would Airtable provide json/csv data pull? What's the limit on requests?

**Comment by pbteja1998** [comment]
@bee-rickey yes, you can create a table by uploading csv. Or you can just copy and paste the entire data from sheets to airtable, it will automatically spread across the cells.

The API is limited to 5 requests per second per base. If you exceed this rate, you will receive a 429 status code and will need to wait 30 seconds before subsequent requests will succeed. But their official Javascript client has built in retry logic. 

Or if we want, we can simply use a caching proxy like how you are creating json/csv files now.

**Comment by pbteja1998** [comment]
@bee-rickey Also checkout the following link

"Airtable is making Airtable Pro available for free to any non-political humanitarian group that has formed to work  on COVID-19 relief efforts"

https://airtable.com/shr2yzaeJmeuhbyrD

**Comment by bee-rickey** [comment]
Will see... I think @JunaidBabu is already trying it out. If we see that it's worth the migration, then why not :)

**Comment by pbteja1998** [comment]
JFYI

@bee-rickey econsult team already got access to airtable pro.

**Comment by JunaidBabu** [comment]
This is under discussion. Closing this issue.
