### ISSUE TITLE
Issue : Wrong Data in API

### ISSUE THREAD

**Issue by vivek50** [covid19india/api#154]
Hello,
I'm getting the wrong data for the Gujarat state [v2/state_district_wise.json](https://api.covid19india.org/v2/state_district_wise.json) API.
May Below API help you update data in your DB.
1) POST - [https://gujcovid19.gujarat.gov.in/Home.aspx/GetDistDataForCovid](https://gujcovid19.gujarat.gov.in/Home.aspx/GetDistDataForCovid)
Header : content-type: application/json
2) POST - [https://gujcovid19.gujarat.gov.in/DrillDownCharts.aspx/GetDistDataForLineCovidDisrtict](https://gujcovid19.gujarat.gov.in/DrillDownCharts.aspx/GetDistDataForLineCovidDisrtict)
Header : content-type: application/json

**Comment by bee-rickey** [comment]
Can you explain what you mean by wrong data?

**Comment by vivek50** [comment]
checkout response.
`{
"district": "Ahmadabad",
"active": 1373,
"confirmed": 1373,
"deceased": 0,
"recovered": 0,
"delta": {
"confirmed": 0,
"deceased": 0,
"recovered": 0
}
}
`
check the recovered and deceased data.

**Comment by bee-rickey** [comment]
This is because we currently aren't capturing district level deceased and recovered.

**Comment by vivek50** [comment]
Ok.
So i suggest use above api to update data of gujarat state.
