### ISSUE TITLE
Data in raw_data API has patients with no patient number

### ISSUE THREAD

**Issue by Aniruddha-S-Prasad** [covid19india/api#155]
I'm currently using the patient number as a primary key in my SQLite database. And this problem in the raw_data.json is throwing up sqlite3.IntegrityError exceptions in my python code. Please fix

**Comment by bee-rickey** [comment]
Can you tell which ones are failing so that we can have look?

**Comment by Aniruddha-S-Prasad** [comment]
Apparently the issue has been fixed. My database builder ran without any errors today.
