### ISSUE TITLE
City / District Name - Spelling Mistake

### ISSUE THREAD

**Issue by Dumpp** [covid19india/api#156]
Hello there,

I am not sure that this is an issue or not but I just want to highlight to you. 

I found two - Incorrect or Misspelled district/city name.

1. Ahmadabad - Should be **Ahmedabad**
2. Dohad - Should be **Dahod**

_Ref: Districtwise Sheet In Google Sheets_.

I apologize to take your time If you find this an Irrelevant Issue.

**Comment by bee-rickey** [comment]
Data Issue. Not a bug to be raised here.
