### ISSUE TITLE
Add time stamp for district wise data

### ISSUE THREAD

**Issue by yashwanth2804** [covid19india/api#159]
https://api.covid19india.org/v2/state_district_wise.json

**Comment by bee-rickey** [comment]
What would this time stamp indicate and what's the need?

**Comment by mdmadhu** [comment]
Building the district level data as a time-series would be most helpful. There is already a 'delta' key in the json that appears to track changes without explicitly indicating the time elapsed. To update it in a way similar to the state-wise time series is what is needed.

**Comment by siddhpant** [comment]
+1

**Comment by JunaidBabu** [comment]
District wise daily data is now available in v3 and v4 end points. Kindly use that for further analysis.
