### ISSUE TITLE
Delta calculation not correct as it assumes all delta's are positive

### ISSUE THREAD

**Issue by windlessStorm** [covid19india/api#16]
let currentStatus = row.currentstatus;
      if (currentStatus) {
        stat.confirmed += 1;
        switch (currentStatus) {
          case "Hospitalized":
            stat.active += 1;
            break;
          case "Recovered":
            stat.recovered += 1;
            break;
          case "Deceased":
            stat.deaths += 1;
            break;
        }

Eg: Total active cases in a state can go down, if no new case and more than one recovered case. Delta for "active" should be negative in this case and UI should show down arrow.

Right now its using "current status" value to increment each delta.

**Comment by sudevschiz** [comment]
This logic to compute the Recovered is not correct fundamentally as we are not sure which patient recovered. We simply cannot use this sheet to compute this.

Another logic using the snapshot of yesterday's Statewise numbers has to be used.

**Comment by sudevschiz** [comment]
This has been fixed.
