### ISSUE TITLE
API for covid warriors data.

### ISSUE THREAD

**Issue by mayankbhagya** [covid19india/api#160]
**Is your feature request related to a problem? Please describe.**
Govt of India has released data for corona warriors: https://covidwarriors.gov.in/default.aspx
That should be exposed as an API for devs to develop features around the same.

**Describe the solution you'd like**
Data has to be scraped and dumped in json and csv files and add to covid-api.
Verified that they don't have any APIs powering their solution that can be reused.

**Additional context**
We're starting to work towards it. Will need help in hosting on api.covid19.
![covidwarriors](https://user-images.githubusercontent.com/557860/79695212-33422e00-8293-11ea-8bd7-0042968d0267.png)

**Comment by gyanendrapatro** [comment]
i would be doing it in python

**Comment by sudevschiz** [comment]
Wondering is this would be available somewhere in data.gov.in portal.

**Comment by mayankbhagya** [comment]
@gyanendrapatro for a start you can publish a MxN matrix of (states, metrics) in a json along with a timestamp of when the data was scraped. In case this data changes, we can run the script again and generate another snapshot of the same data.

**Comment by sudevschiz** [comment]
@gyanendrapatro 
Is this data being updated regularly by MOHFW? Could you confirm that first? Is it's static, it may not be useful. If it's quite dynamic - we should capture this information as it will help in doing capacity analysis across states.

**Comment by sudevschiz** [comment]
This data is not rich, unique or recent enough to be included in this API. Anybody who needs it can capture those values from the website directly. Hence, closing.
