### ISSUE TITLE
Data Mismatch between state and district wise new cases(delta) data.

### ISSUE THREAD

**Issue by lakshmi14** [covid19india/api#161]
Found as an error in react:
![image](https://user-images.githubusercontent.com/7721961/80137037-3f462c80-85c0-11ea-9e88-312e035af0d7.png)

Data Mismatch. It shows 5 confirmed case in Punjab and in district wise inside punjab, for Jalandar it says 6 confirmed.

URL : https://api.covid19india.org/data.json
![image](https://user-images.githubusercontent.com/7721961/80136650-a6171600-85bf-11ea-86a8-46811d96dbdf.png)

URL: https://api.covid19india.org/state_district_wise.json
![image](https://user-images.githubusercontent.com/7721961/80136758-cb0b8900-85bf-11ea-819f-8be82e2a89d4.png)

**Comment by sudevschiz** [comment]
Good catch! 
This happened because one case in Jalandhar for day before yesterday was remapped from Amritsar to Jalandhar. I will fix this at data side.

Note to self :  In such situations, need to change yesterday's value in yellow section.
@bee-rickey

**Comment by bee-rickey** [comment]
@sudevschiz Negative deltas do not really mean an issue. Many times these happen due to states relocating patients. MP does this all the while. IMO, nothing to change.

**Comment by sudevschiz** [comment]
Got it. 
I have fixed the issue OP mentioned. So, closing.
