### ISSUE TITLE
URLs are not made available on web page

### ISSUE THREAD

**Issue by DiptanilSaha** [covid19india/api#168]
On the webpage, api.covid19india.org, the URLs are just acting as normal text.
![image](https://user-images.githubusercontent.com/64295441/80271674-fb4a4900-86df-11ea-984a-667e0a8970f2.png)
Kindly refer to the image attached.

**Comment by JunaidBabu** [comment]
Those links are not meant to be opened in browser. Disabled hyperlinks by design.

**Comment by DiptanilSaha** [comment]
I got it!
