### ISSUE TITLE
States missing in state_test_data

### ISSUE THREAD

**Issue by jishnub** [covid19india/api#176]
In [state_test_data.json](https://api.covid19india.org/state_test_data.json) only three states/UTs show up: Andaman and Nicobar Islands, Andhra Pradesh and Arunachal Pradesh. The other states are missing. This problem suddenly occurred this morning

**Comment by sudevschiz** [comment]
This was due to a blank row in between. Thanks for reporting. We have fixed it now! Please reopen if you are facing the issue still.
