### ISSUE TITLE
27th Apr states_daily.json Incorrect

### ISSUE THREAD

**Issue by vivekr316** [covid19india/api#177]
The https://api.covid19india.org/states_daily.json is repeating 26th-Apr information for 27th-Apr as well on all 3 status - confirmed, recovered and deceased.

**Comment by sudevschiz** [comment]
Thanks for reporting! This was due to a trigger running earlier than expected. I have fixed it.

**Comment by vivekr316** [comment]
Thank you for the prompt response!
