### ISSUE TITLE
JSON object as structure of Arrays

### ISSUE THREAD

**Issue by surabibio** [covid19india/api#179]
https://api.covid19india.org/states_daily.json is in an array of structures format that needs to be parsed and converted to a structure of Array to be given to chart tools like chart.js.

It can be presented directly as a SOA so that creating dashboard and displaying graphs would be one step easier.
e.g states_daily{
 date: [],
tt {
new:[],
deceased: [],
recovered : [],
},
mh {
new:[]
….

**Comment by skavinvarnan** [comment]
I guess this cannot be changed as multiple other apps will relay on this data. Instead it can be v2 just like how ```v2/state_district_wise.json``` is done. 

A neat structure can look like this
```json
[
    {
      "date": "14-Mar-20",
      "states": [
        {
          "stateCode": "AN",
          "confirmed": 10,
          "recovered": 10,
          "deceased": 10
        },
        {
          "stateCode": "MH",
          "confirmed": 10,
          "recovered": 10,
          "deceased": 10
        },
        ...
      ]
    },
    {
      "date": "15-Mar-20",
      "states": [
        {
          "stateCode": "AN",
          "confirmed": 20,
          "recovered": 20,
          "deceased": 20
        },
        {
          "stateCode": "MH",
          "confirmed": 30,
          "recovered": 30,
          "deceased": 30
        },
        ...
      ]
    }
  ]
```

V2 json's url can be link this https://api.covid19india.org/v2/states_daily.json

@ Owners, let me know if something like this OK. I can do and create a Pull Request

**Comment by surabibio** [comment]
Thanks for taking up the request. However your proposed structure does not solve my request which is to minimise the frontend developer restructuring of data. Please have a look at how chart.js (or rather any graph tool) requires data.

**Comment by skavinvarnan** [comment]
Checked chart.js the data will look like this

```
labels: dateArray,
chart1: activeArray,
chart2: recoveredArray,
chart3: deathArray,
```

As chart.js dataset is a bit weird, its better to do that last step processing in the client side

**Comment by surabibio** [comment]
In that case your proposed structure I am afraid has no value addition to my request.

**Comment by piyush-repo** [comment]
@skavinvarnan Better to add the aggregation at the API level and which can be consumed directly but in order to utilize the same API better to have a flag based on which backend can take the decision to send the aggregated response or verbose one.

@surabibio Does that make sense and moreover cost is the only factor which will decide on which side we need to do the desired operation.

**Comment by surabibio** [comment]
Kavin has well understood my request, but finds that structure 'weird'. His proposed structure for R2 is a lot more organised for a human, but still not beneficial for a macine My request is solely for computational efficiently,

**Comment by JunaidBabu** [comment]
v3 and v4 end points should cover most of the requirements.  Closing this issue.
If there is any specific requirement on new data format, please reopen this issue.
