### ISSUE TITLE
Graphql API's for covid19india

### ISSUE THREAD

**Issue by skavinvarnan** [covid19india/api#185]
In reference to the issue #158 

Graphql API's specific for India has been created from the data provided [here](https://github.com/covid19india/api#json)

**Take a look at the detailed document here https://github.com/COVID19-SARS-CoV-2/web-covid-api/blob/master/india_apis.md**

Notes
1. Data is updated once in 3 mins
2. The current server can handle a load of 1000 requests second. In theory the server can handle 840million requests a day.

**Comment by bee-rickey** [comment]
Awesome! Looks like a good one. Where is the server hosted?

**Comment by skavinvarnan** [comment]
Thanks 😀. Its hosted in Digital Ocean (Bangalore Datacenter)

**Comment by JunaidBabu** [comment]
@skavinvarnan which all endpoints of api.covid19india.org are you using to update your database?

**Comment by skavinvarnan** [comment]
These 4 jsons
```
https://api.covid19india.org/data.json
https://api.covid19india.org/state_district_wise.json
https://api.covid19india.org/states_daily.json
https://api.covid19india.org/state_test_data.json
```
