### ISSUE TITLE
Largely Inconsistent data for status of patients in Raw Json API

### ISSUE THREAD

**Issue by jyoti291** [covid19india/api#189]
**API** https://api.covid19india.org/raw_data.json

**Issue** 

The API provides data of patients till 26 April.The provided result of raw data API is largely inconsistent with respect to one of the most important data i.e the current status of the patients.

- The number of deceased patients is only 52 in API data
- The number of recovered patients is only 181 in API data

**Reference** : https://www.businesstoday.in/current/economy-politics/coronavirus-india-live-updates-delhi-mumbai-rajasthan-shops-open-lockdown-26-apr/story/402026.html

**Solution** :  Many applications are using this API for patients data until 26 April.So correct information with respect to the status of patients should be provided in the API so that correct picture of status of patients should be reflected in the same.

**Comment by sudevschiz** [comment]
raw_data.json is just a concatenation of raw_data1 and raw_data2. Please do refer to the details provided at https://api.covid19india.org/csv/

Also, another discussion along the same line is happening in https://github.com/covid19india/api/issues/195. If you have further questions, please do ask there.
Thanks for using the data!
