### ISSUE TITLE
Stale data on raw data API

### ISSUE THREAD

**Issue by faisalchishtii** [covid19india/api#19]
When I aggregate the results from raw data API - https://api.covid19india.org/raw_data.json - I get below:

**Recovered:** 25
**Migrated:** 1
**Deceased:** 15
**Hospitalized:** 712
**Total:** 753 (Adding above four)

Seems like positive cases are being marked **Hospitalized** correctly but not when **Recovered** or **Deceased**. 

![image](https://user-images.githubusercontent.com/26409919/77732946-ff753f00-702b-11ea-86b1-bdb54ef03981.png)

**Comment by JunaidBabu** [comment]
This is because we are unable to trace which patient status was changed. This is a known issue.
