### ISSUE TITLE
Collaboration with covid19india

### ISSUE THREAD

**Issue by jyoti291** [covid19india/api#191]
As an institution Srijan is actively trying to do COVID-19 related Initiative. We primarily deal with community and collaborative platforms. We are deeply interested in supporting Covid-19 initiative. We have identified a few issues with the covid19india ongoing project

- Collaboration Interface(Google Sheet)
- Platform project has fewer activity
- Patients Data APIs has been partitioned into multiple APIs

We have already built a platform to solve the above issues and we are interested to give it as a pro bono. We can host the application for you. We can also build a highly maintainable API gateway service and data module over it. You can make a rest API on the Complete patient database. It will solve some of the problems of data which the consumers of the current platform have been facing. 

Over and beyond we can also put effort to set-up the graphQL and OData layer over it if you promise to use it. Whatever application we have built we are ready to open-source.
We are actively working on publicising this data with the state governments. Also, trying to reach out to the research institute for research activity based on patient data for similar outbreaks. 
We would like you to give a demo of the application and onboard your team. You can access the application using the below link : [https://covid19database.srijan.net](https://covid19database.srijan.net/)

**Comment by bee-rickey** [comment]
@jyoti291 Hi! This is interesting. Is the code open source? We have kept everything open for everyone to view so we would like it to continue that way :). Also, some of the things pointed out by you as issues are actually choices we've made to reduce complexity and maintenance for data updates. Thanks for this initiative :)

**Comment by jyoti291** [comment]
@bee-rickey : This application is build for open source community.The code is not public but we can make it public if you want to have a look on it.We would like you to view the system and if you find it useful, you can use it to maintain the patient's data in the application itself.Let me know if you have any inputs on the same.

**Comment by sudevschiz** [comment]
@jyoti291 I had a quick look at the website link you provided. Great job!

However, our data update process is just too dynamic to be relied upon an external software. We make do with the functionality of Google sheets and around it. For now, it has to remain that way, so that we can adapt to change scenarios. Thanks for reaching out.
