### ISSUE TITLE
API for district-wise daily count.

### ISSUE THREAD

**Issue by Abhishekbhatia** [covid19india/api#192]
I have created a python script to read the raw_data file to show data of daily number of cases for a district in a state.
It will help to create a graph to show daily count of cases for a district of a state.

Frontend graph discussion link :  https://github.com/covid19india/covid19india-react/issues/1391

Screenshot for ref 
![image](https://user-images.githubusercontent.com/5922112/80722190-bb8ac380-8b1c-11ea-9606-7838605b9438.png)

**Comment by Abhishekbhatia** [comment]
I have further enhanced the script to get the daily number of hospitalised cases from all the three raw_data files.

Below is a JSON snippet for Gujarat:

```
"Gujarat": {
        "Surat": {
            "21/03/2020": 2,
            "23/03/2020": 1,
            "24/03/2020": 1,
            "25/03/2020": 2,
            "26/03/2020": 1,
            "29/03/2020": 1,
            "31/03/2020": 1,
            "01/04/2020": 2,
            "04/04/2020": 1,
            "05/04/2020": 3,
            "06/04/2020": 3,
            "07/04/2020": 3,
            "08/04/2020": 1,
            "09/04/2020": 1,
            "10/04/2020": 3,
            "11/04/2020": 1,
            "13/04/2020": 5,
            "14/04/2020": 9,
            "15/04/2020": 9,
            "16/04/2020": 37,
            "17/04/2020": 52,
            "18/04/2020": 13,
            "19/04/2020": 89,
            "20/04/2020": 27,
            "21/04/2020": 78,
            "22/04/2020": 68,
            "23/04/2020": 41,
            "24/04/2020": 6,
            "25/04/2020": 34,
            "26/04/2020": 30,
            "27/04/2020": 30,
            "28/04/2020": 14,
            "29/04/2020": 31,
            "30/04/2020": 13
        },
        "Ahmadabad": {
            "20/03/2020": 2,
            "21/03/2020": 2,
            "22/03/2020": 3,
            "23/03/2020": 6,
            "28/03/2020": 3,
            "29/03/2020": 4,
            "30/03/2020": 1,
            "31/03/2020": 1,
            "01/04/2020": 8,
            "03/04/2020": 7,
            "04/04/2020": 7,
            "05/04/2020": 8,
            "06/04/2020": 11,
            "07/04/2020": 19,
            "09/04/2020": 59,
            "10/04/2020": 55,
            "11/04/2020": 46,
            "12/04/2020": 39,
            "13/04/2020": 38,
            "14/04/2020": 53,
            "15/04/2020": 77,
            "16/04/2020": 95,
            "17/04/2020": 78,
            "18/04/2020": 239,
            "19/04/2020": 239,
            "20/04/2020": 147,
            "21/04/2020": 125,
            "22/04/2020": 128,
            "23/04/2020": 151,
            "24/04/2020": 169,
            "25/04/2020": 182,
            "26/04/2020": 178,
            "27/04/2020": 198,
            "28/04/2020": 164,
            "29/04/2020": 234,
            "30/04/2020": 249
        },
```

**Comment by sudevschiz** [comment]
This is great! Would love look further into the process that you used. However, using the raw_data for this calculation might not bode well as district information was not so available before. Now we have `https://api.covid19india.org/v2/state_district_wise.json` giving the live status of districts. That could possibly be snapshot, to create this daily time series?

Even then, we have to remap the districts in some cases - how can we automatically make those corrections in the timeseries too. Let me know your thoughts.

**Comment by vntkumar8** [comment]
> I have created a python script to read the raw_data file to show data of daily number of cases for a district in a state.
> It will help to create a graph to show daily count of cases for a district of a state.
> 
> Frontend graph discussion link : [covid19india/covid19india-react#1391](https://github.com/covid19india/covid19india-react/issues/1391)
> 
> Screenshot for ref
> ![image](https://user-images.githubusercontent.com/5922112/80722190-bb8ac380-8b1c-11ea-9606-7838605b9438.png)

@Abhishekbhatia  can you share the script, It will help us

**Comment by Abhishekbhatia** [comment]
@sudevschiz : I looked at the API results for https://api.covid19india.org/v2/state_district_wise.json.
The only shortcoming is that there are no date fields/keys in this api results. It only gives the district wise total count of cases without any dates. 
If we are only going to be dependent on this API results for the date-wise district-wise results then we may have to store this data in the DB datewise. But, then also we may not have historic data.

I have used the 3 raw data json, because it had all the dates for the districts in a state. Let me give you a summary of how the JSON data is being formed.

1. Since raw_data1.json and raw_data2.json is similar in structure i am using the "dateannounced" key as my counter for the number of cases for a date in a district of a state.

2. For raw_data3.json, i am checking the "currentstatus" for each data. If it is "Hospitalised", then get the value of "numcases" for a date in a district of a state.

I am storing all the information created with above 2 approaches in a separate JSON file.

I am going to add the scripts in the codebase and will create a pull request for a review.

**Comment by Abhishekbhatia** [comment]
@JunaidBabu @sudevschiz 

I am not able to add the scripts in the codebase. I have created a different branch! Attached is a screenshot of the error.

![image](https://user-images.githubusercontent.com/5922112/80915162-018a9600-8d6e-11ea-9db9-3b3527e70f82.png)

**Comment by sudevschiz** [comment]
Have your created a fork of the repository to your own github space?
You have to push the changes to that repo and then make a Pull Request to this original repo. We will review it and then merge it.

**Comment by Abhishekbhatia** [comment]
Thanks @sudevschiz :

Created a pull request : https://github.com/covid19india/api/pull/202

**Comment by JunaidBabu** [comment]
#202
