### ISSUE TITLE
Discrepancy in dashboad number and datasets provided!

### ISSUE THREAD

**Issue by mrinal000** [covid19india/api#193]
Why the number of cases shown in covid19india.org does not agree with the cumulative data of 

https://api.covid19india.org/csv/latest/raw_data1.csv 
https://api.covid19india.org/csv/latest/raw_data2.csv
https://api.covid19india.org/csv/latest/raw_data3.csv

What am I missing?
 
Thanks,
Mrinal

**Comment by skyprince999** [comment]
had raised a similar concern - 

https://github.com/covid19india/covid19india-react/issues/1680

**Comment by sudevschiz** [comment]
I have added more context in the landing page of api.covid19india.org/csv 
Please do have a look and for more discussions, use this thread : https://github.com/covid19india/api/issues/195

Thank you.
