### ISSUE TITLE
[Query] Questions regarding changes to raw_data API (CSV/JSON)

### ISSUE THREAD

**Issue by skyprince999** [covid19india/api#195]
**Describe the bug**
CSV files available at https://api.covid19india.org/csv/ not updated. 
the recent pull from the data shows the csv is updated only until 26th April

EDIT: I believe the JSON files are updated (30th April). Any reason why the csv file is not?

**To Reproduce**

1. Go to https://api.covid19india.org/csv/
2. Download the raw_data.csv file
3. Open the file & check for `Date Announced` column

else please check the kaggle notebook 
https://www.kaggle.com/skylord/real-time-tracking-of-r-t-for-indian-state
 

**Expected behavior**

Expecting daily updates on the csv files. It's easier to take a csv file & process it

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version NA

**Comment by sudevschiz** [comment]
> EDIT:
Did a deep dive, in the new file (raw_data3.csv) you have stopped adding individual case counts. Instead a new column Num Cases has been added.
So for calculating for new cases for states per day, I have to take the following steps

remove Deceased and Recovered rows [ this is from column Current Status]
sum up the Num Cases. group by state name & date

You have to do one more step in raw_data1 and raw_data2 : Reset all the Current Status in 1&2 with "Hospitalized"

I made a quick note of steps here: https://api.covid19india.org/csv/#notes

However, there are few more nuances to this data wrangling operation. I'll try to work on it this weekend. Help is welcome :)

**Comment by skyprince999** [comment]
@sudevschiz 
How can I help? Using python script I have concatenated all the three files. Should I make a pull request on that? 
Also, should this issue be moved to the /api repo?

**Comment by sudevschiz** [comment]
Oh nice. Could you point me to your fork? There are lot more considerations. I can have a look at it and then comment?

**Comment by skyprince999** [comment]
Its a python notebook. Added it to my branch. have a look.  

https://github.com/skyprince999/api/blob/master/notebook-for-data-wrangling.ipynb

**Comment by JunaidBabu** [comment]
This is already taken care using internal scripts. The new json and csv files should have updated information.
