### ISSUE TITLE
National total not updated properly. Increase in number of west bengal not added.

### ISSUE THREAD

**Issue by ff171217** [covid19india/api#198]
The increase in the number of total cases in west bengal from yesterday which is 127 has not been added to the national total. Although the total cases for west bengal is being shown as 922 whereas yesterday it was 795. The same is true for the number of discharged persons. Please update the national figures.

**Comment by bee-rickey** [comment]
Hi can you clarify which national total is it not added to? It's already part of the 39k total across the country.

**Comment by ff171217** [comment]
No it is not. Yesterday the final tally of total infected cases pan India stood at 39829. Today till 3pm 190 more cases have been reported from Rajasthan..60 Andhra Pradesh..58. Karnataka..5 Bihar..1 Haryana..45 Odisha..2 Ladakh..19 ..there is no addition of the increase in number of cases from west bengal from yesterday till today which is 127... It was 795 yesterday then numbers increased to 922 as per Ministry of health.. govt of India... The increase in the count was not incorporated in your yesterday's figures and neither on today's figures.  Please check

**Comment by ff171217** [comment]
#
![Screenshot_2020-05-03-12-25-56-74](https://user-images.githubusercontent.com/64362506/80910880-30920f00-8d50-11ea-93c0-2cf61dd84c8d.jpg)
![Screenshot_2020-05-03-14-58-19-60](https://user-images.githubusercontent.com/64362506/80910882-325bd280-8d50-11ea-9ef5-a11b49d79aee.jpg)
![Screenshot_2020-05-03-14-57-47-09](https://user-images.githubusercontent.com/64362506/80910883-32f46900-8d50-11ea-8e2a-42297d22f4e2.jpg)
![Screenshot_2020-05-03-14-58-07-95](https://user-images.githubusercontent.com/64362506/80910884-338cff80-8d50-11ea-9bb0-97b813910e3c.jpg) . please look at these screenshots

**Comment by ff171217** [comment]
I can now see that you had updated the figures of west bengal post midnight yesterday. I had informed your organization through my comment section yesterday.So my query has been resolved. Thanks for responding
