### ISSUE TITLE
I would suggest changing name of "Gautam Buddha Nagar" to "Gautam Buddh Nagar" as it is according to google maps data.

### ISSUE THREAD

**Issue by harshit741** [covid19india/api#199]
I used geocoding to return location and than tally them to your api data, many things didnt worked out well. One of which is this issue, geocoding returned Gautam Buddh Nagar but the api has Gautam Buddha Nagar. I had to write seperate rule for that.

**Comment by sudevschiz** [comment]
District names were fetched from here http://districts.nic.in/districts.php?sid=UP and then later corrected by some volunteers from UP. Let's retain it that way.
Good job with the separate rule :)

**Comment by harshit741** [comment]
I think I should raise similar issue to Google Maps to return data according to district.nic.in 😂

**Comment by bee-rickey** [comment]
@harshit741 That might be a good idea :P Given that the Indian govt data remains stagnant for the longest of times ;)
