### ISSUE TITLE
Enhancement on data listing

### ISSUE THREAD

**Issue by imanshul** [covid19india/api#2]
Add codes to states like : "state_code" : "DL" so that we can filter the data out.
Also the structure should be :
{"state" : "Delhi",
"state_code" : "DL",
"data" : [{
 "name" : "East Delhi",
 "confirmed_Cases" : 30
.
.
.
 }, 
 {
 }
..
 ]
}

**Comment by sudevschiz** [comment]
Can you add more details like which API you're talking about?

If possible show how the API response looks like before and after the change.

Please use code formatting. Thank you!

**Comment by JunaidBabu** [comment]
Already using standard names for states.

**Comment by imanshul** [comment]
What I was talking about is follow a standard so that it is easy to filter out things using a particular identifier instead of throwing name as object name.

My suggestion is use a standard something like below : 


{
	"stateData": [{
			"districtName": "Kerala",
			"stateCode": "KL",
			"districtData": [{
				"districtName": "Wayanad",
				"districtCode": "03",
				"confirmed": 1,
				"lastupdatedtime": 1585285614141
			}, {
				"districtName": "Thrissur",
				"districtCode": "07",
				"confirmed": 5,
				"lastupdatedtime": 1585285614141
			}]
		},
		{
			"districtName": "Delhi",
			"stateCode": "DL",
			"districtData": [{
				"districtName": "East Delhi",
				"districtCode": "04",
				"confirmed": 1,
				"lastupdatedtime": 1585285614141
			}, {
				"districtName": "South West Delhi",
				"districtCode": "08",
				"confirmed": 3,
				"lastupdatedtime": 1585285614141
			}]
		}
	]
}
