### ISSUE TITLE
need help to use this api in a IOT display

### ISSUE THREAD

**Issue by Soumojit28** [covid19india/api#20]
I am trying to create a LED matrix and a 2line Display that will display the live data using ESP8266 microcontroller, Is there any way to just only get the total data like - total confirmed case, total recovered, etc via the API, cause it will be hard to decode that much data using small microcontrollers.

**Comment by d3v7** [comment]
if u want, I can create one only for the total confirmed case, total recovered and total deaths.

**Comment by Soumojit28** [comment]
That will be very helpful, Also add total active cases, and also please make it accessible via Http, cause its difficult to use https in ESP8266.

**Comment by d3v7** [comment]
try this and let me know
http://coronago.xyz/data.json

**Comment by aamin3189** [comment]
This is awesome, just wanted to know if I can use your API in my project [COVID-19 Tracker PWA](https://github.com/aamin3189/covid)

**Comment by d3v7** [comment]
open-source feel free to use

**Comment by utkarsh1996** [comment]
Hi,
want to ask that I want to use these api's to fetch the data.
Just want to confirm whether these api's will be available in coming days or shall I use the csv??

**Comment by Soumojit28** [comment]
@d3v7  Thanks for this awesome API, I successfully created an ESP8266 IoT display, Is it possible to add some other things like state-wise data, Like total numbers from westbengal etc.

**Comment by d3v7** [comment]
yes sure i will add it soon.

**Comment by utkarsh1996** [comment]
> open-source feel free to use

Hi, want to ask that are these api available in future or you have any plans to put it down, as I am using them to gather the data.

**Comment by d3v7** [comment]
> > open-source feel free to use
> 
> Hi, want to ask that are these api available in future or you have any plans to put it down, as I am using them to gather the data.

actually I have no idea. the owner may keep it for a year or something I guess .
@someshkar @JunaidBabu

**Comment by someshkar** [comment]
It should be up for quite a while, don't hesitate to use it!

**Comment by utkarsh1996** [comment]
> It should be up for quite a while, don't hesitate to use it!



> It should be up for quite a while, don't hesitate to use it!

okay, thanks.

**Comment by Soumojit28** [comment]
@someshkar @JunaidBabu add this API also in the readme, so others can easily find it.

**Comment by JunaidBabu** [comment]
Out of scope. Closing

**Comment by utkarsh1996** [comment]
> @someshkar @JunaidBabu add this API also in the readme, so others can easily find it.

Hi, raw_data api giving CORS when I am using it to retrieve data.
