### ISSUE TITLE
Tested data is not available from 20th of April to 23thrd of April 

### ISSUE THREAD

**Issue by sureshpal** [covid19india/api#201]
Tested data is not available from 20th of April to 23thrd of April .
Please have a look ..

Please find the attachment.
![Screenshot_2020-05-04-06-31-56-033_com android chrome](https://user-images.githubusercontent.com/8362713/80930692-c5d5e780-8dd2-11ea-909a-12ac9c5b0302.jpg)

**Comment by sudevschiz** [comment]
This is because ICMR did not publish the information on those dates.
