### ISSUE TITLE
Csv file is not having data upto date

### ISSUE THREAD

**Issue by cpkabra** [covid19india/api#203]
Hi Team,
You mentoned that csv file is available in this pattern and this url is having live data but i have looked at it and it is having data till 26 April.
api.covid19india.org/csv/latest/raw_data.csv

**Comment by sudevschiz** [comment]
Could you have a look at this page and see if it clears your questions?
https://api.covid19india.org/csv/

**Comment by cpkabra** [comment]
Hi Sudevschiz,

Yup this link helped me. Thanks for sharing
