### ISSUE TITLE
Chief Secretary of West Bengal declares revised and updated numbers of covid patients in state

### ISSUE THREAD

**Issue by ff171217** [covid19india/api#204]
The chief secretary of west bengal has just now declared in press meeting that total number of covid cases in west bengal is 1259 and total active cases is 908.
Please keep an eye on the state bulletin this evening and update figures.

**Comment by sudevschiz** [comment]
Yep. Noticed the same. Will keep an eye out for the bulletin and update accordingly!
You can reach us through the form here for queries like this : https://forms.gle/XLFc6LhVEUtE25Pz6

Thank you!
