### ISSUE TITLE
Use number plate abbreviations for state code

### ISSUE THREAD

**Issue by siddhpant** [covid19india/api#218]
It is not the case for:
- Uttarakhand (uses UT instead of UK),
- Chhattisgarh (uses CT instead of CG),
- Telangana (uses TG instead of TS), and
- Dadra and Nagar Haveli and Daman and Diu (uses DN instead of DD)

Also, the DD abbreviation is redundantly associated with Daman and Diu despite the merger of Union territories being reflected.

**Comment by ims-devops-practice** [comment]
Changing now will break many existing applications which are already dependent on the current abbreviation.

**Comment by arghyadeep-k** [comment]
Changing now will break many existing applications which are already dependent on the current abbreviation.

**Comment by siddhpant** [comment]
Oh okay, understandable.

Though, hard-coding abbreviations instead of full state name when it is available is anyways a bad practice.

**Comment by arghyadeep-k** [comment]
If that's the case, ids shouldn't be used anywhere. Full names are present almost always but still we need an unique identifier.

**Comment by sudevschiz** [comment]
State Codes are based on this ISO standard :  https://en.wikipedia.org/wiki/ISO_3166-2:IN and not based on the Motor Vehicle Department codes. 

Case of DD & DNH is very recent and it was decided to use DN state code.

**Comment by siddhpant** [comment]
Alright
