### ISSUE TITLE
Data refresh strategy 

### ISSUE THREAD

**Issue by harjeetxeno** [covid19india/api#22]
I see a lot of data update commits. 
What's the process ?? After the moderators confirm the reported case is correct, someone executes "pushthejson" script and then all the JSON are updated   ?? 
If my understanding is correct here, may I help to improve this process if you guys feel that is needed?

**Comment by sumitmckv** [comment]
@harjeetxeno, Please have a look at https://github.com/covid19india/api/blob/1eb576adaa4c115cf8694119a531a1db653f8daf/.github/workflows/javascript.yml

**Comment by JunaidBabu** [comment]
Using github actions to run the script periodically 
https://github.com/covid19india/api/actions
