### ISSUE TITLE
Completing case wise data

### ISSUE THREAD

**Issue by siddharthsrivastava** [covid19india/api#223]
While analysing the patient jsons, I noticed that the gender information is missing from a majority of the cases. For example, till  26 April 27891 cases were there containing gender information for 5313 cases only. 

Is it possible to make the data complete, so that it will also help the data scientists and the people using it via Kaggle.

**Comment by bee-rickey** [comment]
This is purely based on the info provided by the state bulletins. Nothing much we can do in this unfortunately.
