### ISSUE TITLE
Telangana latest data

### ISSUE THREAD

**Issue by rojohyd** [covid19india/api#227]
This is the official site for Telangana Covid details http://124.124.103.93/COVID/home.htm
There was a ticker initially which shows the latest confirmed/active/deaths and samples tested
This is being hidden with a CSS style, but the data is still available and updated frequently(<hour, almost latest )
This can be used to update the latest data
I've extracted this info in a separate site which basically picks up the same data, and un-hides it
https://flirtatiousshirt.htmlpasta.com/

will you please update in the CSV the latest data, always
The samples tested is being shown in existing site is old
![COVID_19](https://user-images.githubusercontent.com/44604722/81528717-ff7e9380-937a-11ea-8e01-f08f3c4c314e.jpg)

**Comment by sudevschiz** [comment]
Thanks for highlighting this source. Sadly, we can't credibly use and report this information as it's a hidden element in a website.
