### ISSUE TITLE
Admin can you list my android project as it is using this api. 

### ISSUE THREAD

**Issue by Shiba-Kar** [covid19india/api#228]
[This is the link](https://github.com/Shiba-Kar/covid-19_tracker)

**Comment by gouenji-shuuya** [comment]
Is it required for the project to be open-sourced to be listed here?

**Comment by sudevschiz** [comment]
Not required to be opensourced. However, please do mention this repo as a source somewhere in this page. @Shiba-Kar you can make a PR updating the README and I will add it to the page. Thank you.

**Comment by sudevschiz** [comment]
Have you already made a PR and is it merged now? If that's the case. Please close this issue.  @Shiba-Kar
