### ISSUE TITLE
Add geocoded resources.json

### ISSUE THREAD

**Issue by aswaathb** [covid19india/api#231]

**Comment by JunaidBabu** [comment]
Could you please elaborate?

**Comment by sudevschiz** [comment]
I'm working with @aswaathb to provide geocoded feature object for each row in essentials. This is for the location based nearby essentials feature. @aswaathb already has a python script to get the data in the format he needs it. https://github.com/aswaathb/covid19india-react/blob/publish/newResources/src/geocoder.py 

Resulting json would look like this : 
```
// 20200513121710
// https://raw.githubusercontent.com/aswaathb/covid19india-react/publish/newResources/src/geoResources_unmerged.json

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": 0,
        "name": "Regional Medical Research Centre (ICMR)",
        "desc": "Government approved and supported Testing labs by ICMR",
        "geoTag": "Port Blair",
        "addr": "Port Blair, Andaman and Nicobar, India",
        "state": "Andaman & Nicobar",
        "phone": "3192251158,\n3192251159",
        "contact": "http://rmrc.res.in/",
        "priority": 1,
        "icon": "lab"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          92.75,
          11.66667
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
```

He will be updating that script further. @JunaidBabu Once he's done, can we do the geocoding only for the 'new' entries in the essentials sheet by comparing it with the previously geocoded json?

**Comment by aswaathb** [comment]
Thanks for the explaination @sudevschiz, I tried to delete the issue after we spoke and about this.

@JunaidBabu, #240 has the revised script

**Comment by sudevschiz** [comment]
Done and dusted. 👍
