### ISSUE TITLE
Add district AMRELI in Gujarat

### ISSUE THREAD

**Issue by nileshbandhiya** [covid19india/api#232]
Kindly add district Amreli in Gujarat state. Currently dashbaord not showing said district in Gujarat state. Although there is no active case currently, but it will be nice if you will add the district.

Thanks you are doing a grate job...

**Comment by sudevschiz** [comment]
This is done now. We are displaying all the districts, even if there are no cases there.

**Comment by nileshbandhiya** [comment]
Thanks. One more suggestion:  While clicking on some State (like Gujarat), it shows "other state" figure. I cannot understand it. If it is not necessary, kindly remove it if possible.
