### ISSUE TITLE
Incorrect: mismatch in active cases

### ISSUE THREAD

**Issue by acharan91** [covid19india/api#239]
![2E7BBDA1-9252-4CD2-9773-D2B1D2E7FA9F](https://user-images.githubusercontent.com/65415204/82077699-7a3e0a80-96fd-11ea-8903-5d724f2a6ecd.jpeg)

**Comment by acharan91** [comment]
Count of active cases in Hyderabad is 572
and total active cases in Telangana is 461

**Comment by sudevschiz** [comment]
Could you sum up the -372 in Unknown active cases too?
