### ISSUE TITLE
The API response does not look like properly formatted JSON data?

### ISSUE THREAD

**Issue by ScuderiaAirlines** [covid19india/api#24]
There are no square brackets. Nor is this data properly iterable in JS via "key in" or any other method. I'm talking about state_district_wise. Not being able to access the keys numerically, say data[0] instead of typing data['Kerala'] is a problem when there is even more nested data, and no state-wise summary is available - in which case I would have reluctantly hard-coded the 28 values..

Or maybe I'm not knowledgeable enough, will appreciate some help.

**Comment by sumitmckv** [comment]
@ScuderiaAirlines try to iterate state_district_wise something like this to get state-wise summary.
```
const data = require('./state_district_wise');

const stateWiseSummery = Object.keys(data).map(state => {
    let districtData = data[state].districtData;
    return {
        state,
        confirmed: Object.keys(districtData).reduce((total, district) => {
            return total + districtData[district].confirmed;
        }, 0)
    }
});

console.log(stateWiseSummery);
```
Also check statewise section in
https://github.com/covid19india/api/blob/0fe91d81d19d4959da2a9b0a717a7d69846027e2/data.json#L536-L564

**Comment by ScuderiaAirlines** [comment]
Thank you so much @sumitmckv! I should have checked all the json files. This solves my issue. I'll close it now.
