### ISSUE TITLE
-2 active cases in Buldhana District (Maharashtra)

### ISSUE THREAD

**Issue by shubhams2m** [covid19india/api#241]
I just downloaded district wise CSV from https://api.covid19india.org/csv/latest/district_wise.csv. And it has -2 active cases in Buldhana District of Maharashtra (District_Key - MH_Buldhana).

**Comment by sudevschiz** [comment]
This was because MH govt. dashboard was reporting the same way. Looks like this is fixed now on the website and the csv should reflect the same in the latest version. Please check.

**Comment by bee-rickey** [comment]
Can't do much about these since this data is from the state dashboards. Closing this for now.
