### ISSUE TITLE
Python script to create a single JSON dump for total cases and tests conducted till date

### ISSUE THREAD

**Issue by Manik-Jain** [covid19india/api#247]
This Python script aims to create and download a JSON based report that helps to:

1. Map each raw value to the respective State and district level at each date
2. the total states cases for each district on that date
3. total cases for any state till date
4. Covid tests conducted for each state on all dates
5. total cases in the country till date

State : {
 District1: {
          Date 1 : { 
               'hospitalized' : count,
               'recovered' : count,
               'deceased' : count,
            stateCases : {
               'hospitalized' : count,
               'recovered' : count,
               'deceased' : count,
             }
            }, 
         Date 2 : { 
               'hospitalized' : count,
               'recovered' : count,
               'deceased' : count,
             stateCases : {
               'hospitalized' : count,
               'recovered' : count,
               'deceased' : count,
             }
            }
         ........ and so on
       },
District2: {
          Date 1 : { 
               'hospitalized' : count,
               'recovered' : count,
               'deceased' : count,
            stateCases : {
               'hospitalized' : count,
               'recovered' : count,
               'deceased' : count,
             }
            }, 
         Date 2 : { 
               'hospitalized' : count,
               'recovered' : count,
               'deceased' : count,
             stateCases : {
               'hospitalized' : count,
               'recovered' : count,
               'deceased' : count,
             }
            }
         ........ and so on
       }, 
      stateCases : {
               'hospitalized' : count,
               'recovered' : count,
               'deceased' : count,
             },
   tests_conducted : {
      Date1 : {
                "positive": 387,
                "negative": 16002,
                "unconfirmed": 86,
                "total_tested": 16475,
                "people_in_quarantine": 522,
                "people_released": "Data not available"
         },
      Date2 : {
                "positive": 394,
                "negative": 16459,
                "unconfirmed": 547,
                "total_tested": 17400,
                "people_in_quarantine": 523,
                "people_released": "Data not available"
       },
"countryCases": {
        "hospitalized": 66954,
        "recovered": 13259,
        "deceased": 1402
    },
    "totalTests": 38751129

}
}

**Comment by sudevschiz** [comment]
Case count from raw data is not straightforward even now due to shifts in the way in which we used to capture the information. A bit more changes in raw data is required to make every moving part go in sync. Working on this!

Closing this issue.

**Comment by Manik-Jain** [comment]
Hi,

This is a bit weird that the PRs are being reviewed after two months of contribution. 
I understand there may be some issues with the raw data, but this PR is basically aimed at solving those issues only.

Thanks
Manik Jain
