### ISSUE TITLE
Add more documentation to the README

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/api#25]
README can give more context regarding the details in the API

It can also mention a changelog as lot of data fields are getting added to the data.

**Comment by Priyansi** [comment]
Assign this to me. I can help.

**Comment by sudevschiz** [comment]
@Priyansi Please do discuss what details you plan to include.

**Comment by Priyansi** [comment]
I'm sorry but something else came up. Please unassign me.

**Comment by sudevschiz** [comment]
Sure.!

**Comment by cibinjoseph** [comment]
I have a bit of python code that generates trees like so:
```bash
└─ (object)
   ├─ "cases_time_series" (array)
   │  └─ (object)
   │     ├─ "dailyconfirmed" (string)
   │     ├─ "dailydeceased" (string)
   │     ├─ "dailyrecovered" (string)
   │     ├─ "date" (string)
   │     ├─ "totalconfirmed" (string)
   │     ├─ "totaldeceased" (string)
   │     └─ "totalrecovered" (string)
   ├─ "statewise" (array)
   │  └─ (object)
   │     ├─ "active" (string)
   │     ├─ "confirmed" (string)
   │     ├─ "deaths" (string)
   │     ├─ "deltaconfirmed" (string)
   │     ├─ "deltadeaths" (string)
   │     ├─ "deltarecovered" (string)
   │     ├─ "lastupdatedtime" (string)
   │     ├─ "recovered" (string)
   │     ├─ "state" (string)
   │     ├─ "statecode" (string)
   │     └─ "statenotes" (string)
   └─ "tested" (array)
      └─ (object)
         ├─ "positivecasesfromsamplesreported" (string)
         ├─ "samplereportedtoday" (string)
         ├─ "source" (string)
         ├─ "testsconductedbyprivatelabs" (string)
         ├─ "totalindividualstested" (string)
         ├─ "totalpositivecases" (string)
         ├─ "totalsamplestested" (string)
         └─ "updatetimestamp" (string)
```

We could put these pages in a `docs/<APIName>.md` markdown file and provide links to those as documentation for the APIs

**Comment by sudevschiz** [comment]
Yes! We can do this. However an easy document to mention what the fields mean and any caveats regarding that field would be useful too. If you can create a simple template table, I can fill in more details regarding each field. Let me know.

**Comment by cibinjoseph** [comment]
Sure! I'm on it. I'll add the docs pages and send a pull request.

**Comment by cibinjoseph** [comment]
Check if this template is fine [myFork/docs/data.md](https://github.com/cibinjoseph/api/blob/docs/docs/data.md)
I've included a tree structure for showing hierarchy and a table format for extra notes.

Do you want a separate .md file for each API link or are you planning to put them all in one?
**Individual** --> Neater but difficult to search for a specific type of data.
**Single** --> All in one place, but super cluttered, long and ugly.

I would prefer individual files (with a common header template) for each api page and links to them from the front page table in README.md. This would be easier to modify in case of changes or dropping of support for an api.

**Comment by sudevschiz** [comment]
Individual files will be neater, as you mentioned, if we are keeping the tree structure. 
Let's have structured folders within docs and link to those docs in README.md

Go ahead and add the folder structure and hyperlink, I will update the individual .md files.

**Comment by sudevschiz** [comment]
Added more details in api.covid19india.org and api.covid19india.org/csv
Things are still too dynamic to prepare detailed API documentation for each endpoint. Will continue working on this regard

**Comment by sopanlavhale** [comment]
can we configuration swagger-UI for APIs? I can configuration setup if you guys want.

**Comment by ars75** [comment]
I actually actively contributed to the early maintenance of the README file, but let me know if I can help again

**Comment by ars75** [comment]
I was also responsible for the v2 JSON APIs, so I'd love to document it if need be
