### ISSUE TITLE
Thanks for approving the commit but the change is not visible, I think there is some issue!

### ISSUE THREAD

**Issue by rohitxsh93** [covid19india/api#251]
Thanks for approving the commit but the change is not visible, I think there is some issue!

_Originally posted by @rohitxsh93 in https://github.com/covid19india/api/pull/243#issuecomment-630223050_

**Comment by bee-rickey** [comment]
Hi could you please raise the PR on the master again? It was wrongly merged into the gh-pages and hence it's not visible. Thank you!

**Comment by rohitxsh93** [comment]
Done

**Comment by bee-rickey** [comment]
Done.
