### ISSUE TITLE
Doc : Need to correct the COVID-19 Dashboard India Hyperlink

### ISSUE THREAD

**Issue by aman7797** [covid19india/api#263]
![image](https://user-images.githubusercontent.com/30632204/82374204-54d23900-9a3c-11ea-9494-7500ad40e549.png)

**Comment by CHINMAY6656** [comment]
[](url)
![covidss](https://user-images.githubusercontent.com/40867159/82441760-09f80600-9abc-11ea-9eec-daa14b8a3207.png)
is this how it should be ???

**Comment by sudevschiz** [comment]
Fixed this. Thanks for reporting.
