### ISSUE TITLE
Docs: update the CSV listing to indicate raw_data4.csv is available

### ISSUE THREAD

**Issue by satejsoman** [covid19india/api#265]
The json API description mentions raw_data4.json, but the corresponding table in the CSV documentation hasn't been updated yet. Happy to submit a PR to do this - just following contribution guidelines and filing an issue first.

**Comment by sudevschiz** [comment]
Hi, Thanks for reporting. I made the change myself as there was some detail required in updating the same.

Looking forward to your other contributions.

**Comment by satejsoman** [comment]
Thanks!
