### ISSUE TITLE
Small error in state_wise_daily.csv

### ISSUE THREAD

**Issue by frank-chris** [covid19india/api#269]
In the state_wise_daily.csv file, the entry for **MP** for **16-Mar-20, Confirmed (Row 8)** is empty. Not a major issue, try to fix if possible.

**Comment by sudevschiz** [comment]
Is it from the `/latest/` endpoint?

**Comment by frank-chris** [comment]
Yeah, I suppose. This is the link of the file: [https://api.covid19india.org/csv/latest/state_wise_daily.csv](https://api.covid19india.org/csv/latest/state_wise_daily.csv)

**Comment by sudevschiz** [comment]
Just noticed. It's actually a zero value. I have added 0 now. Please reopen if you find that the error persists.

**Comment by frank-chris** [comment]
Yes, it's correct now. Thanks!
