### ISSUE TITLE
states_daily_csv info missing in csv section of api

### ISSUE THREAD

**Issue by hanishkvc** [covid19india/api#286]
Hi,

Even thou states_daily_to_csv generates csv files like
http://api.covid19india.org/states_daily_csv/confirmed.csv.

This api which was originally mentioned in the api's csv section seems missing now. Please update the same. I have even verified this because my code

https://github.com/hanishkvc/prgs-health-covid19-analtoolkit

uses this api to generate covid india related plots.

**Comment by sudevschiz** [comment]
![image](https://user-images.githubusercontent.com/4298868/83704238-8823e300-a64c-11ea-9d4e-dccaec8fffcf.png)
Looks like this is present. Please reopen if you were referring to something else.
