### ISSUE TITLE
Update hotspot zones using new list released by Central Government

### ISSUE THREAD

**Issue by prateek297** [covid19india/api#288]

**Comment by sudevschiz** [comment]
Could you share the this new list?

**Comment by prateek297** [comment]
Can't find the new list anywhere

**Comment by prateek297** [comment]
I'll update if i find one.

**Comment by FrenziedWarrior** [comment]
Just an inquiry, are all state governments maintaining a list of Red, Orange, Green zones at a district level or have they started declaring more granular level zones within a district? 

I am trying to create a time-series for changes in zones at a district level since this classification started.

**Comment by prateek297** [comment]
Yes. They are maintaining a list of "contaminated zone" within the district but there's no list present which has all this data in one place. You can check website of every state ( if they have one ) or reach out to any of your friends in that state.

**Comment by prateek297** [comment]
I am from Jharkhand. We do not have any red zones now. Previously we have one "ranchi", my home town but now it's removed from the updated list. But we do have one contaminated zone here "hindpiri".

**Comment by sudevschiz** [comment]
As hotspots are not published by central government and the containment zones published by states are not in a good shape, we won't be progressing on this activity.
