### ISSUE TITLE
Incorrect Entries in state_wise_daily.csv

### ISSUE THREAD

**Issue by VHKA1729** [covid19india/api#289]
Link: https://api.covid19india.org/csv/latest/state_wise_daily.csv

The latest data (last 4 rows) is corrupted. All the entries have a value of 0 and there is no date.

![image](https://user-images.githubusercontent.com/60542389/82750266-8fd1c500-9dcc-11ea-94d8-9118390231b4.png)

**Comment by sudevschiz** [comment]
This was a temporary measure done while we were switching to a new raw data sheet. This has been fixed now.
