### ISSUE TITLE
Some of the rows has combined UT names:

### ISSUE THREAD

**Issue by ninjakx** [covid19india/api#290]
https://api.rootnet.in/covid19-in/unofficial/covid19india.org/statewise/history
This arises for may data ->   from "day": "2020-05-06", These cases are appeared.
Case1 (combined UT + Daman and Diu separate entity)
```
   {
            "state": "**Dadra and Nagar Haveli and Daman and Diu**",
            "confirmed": 1,
            "recovered": 0,
            "deaths": 0,
            "active": 1
          },
          {
            "state": "Nagaland",
            "confirmed": 0,
            "recovered": 0,
            "deaths": 0,
            "active": 0
          },
          {
            "state": "**Daman and Diu**",
            "confirmed": 0,
            "recovered": 0,
            "deaths": 0,
            "active": 0
          },
```

Case2: (combined UT but no Daman and Diu)

**Comment by sudevschiz** [comment]
As DNH & DD have become a single UT, we have combined them in our api. API that you mentioned is a derived version of the original API. Please do contact the maintainer of the API https://twitter.com/amodm?lang=en if you have further queries.
