### ISSUE TITLE
Introduction about used technologies 

### ISSUE THREAD

**Issue by keshavashiya** [covid19india/api#297]
Please explain about used technologies to create this API, like where this API is hosted and how anyone can develop this type of API.

**Comment by FrenziedWarrior** [comment]
I would like to be assigned this task. I will go through the codebase and follow up with questions. Thanks, if no one else is working on this.

**Comment by keshavashiya** [comment]
It's small description about how this project is started and how server is managing through Github Actions.

https://blog.covid19india.org/2020/06/11/struggle/

**Comment by bee-rickey** [comment]
A detailed description is given here: https://blog.covid19india.org/2020/09/04/architecture/ Closing this issue.
