### ISSUE TITLE
Repeated row for tested_numbers_icmr_data in CSV files table

### ISSUE THREAD

**Issue by DoubleGremlin181** [covid19india/api#314]
The row for "tested_numbers_icmr_data" is repeated in the table [here](https://api.covid19india.org/csv/). The contents and links are exactly the same in both the entires as seen here:

![covid19india_issue](https://user-images.githubusercontent.com/22704006/83325581-d458d700-a28a-11ea-8173-af70c0cc7c3b.PNG)

**Comment by sudevschiz** [comment]
Fixed it. Thanks for reporting!
