### ISSUE TITLE
Inconsistency in the data base files through API

### ISSUE THREAD

**Issue by omkar1610** [covid19india/api#330]
Total data available in all the 6 json files combined is 78k only.
for eg 3rd json file is having 10k entries. It should have at least 30-35k.
Can some one explain me, how to get the rest data?

![image](https://user-images.githubusercontent.com/30653006/83911383-c8d54680-a789-11ea-956a-3da4b1edabca.png)

**Comment by sudevschiz** [comment]
Please read https://api.covid19india.org/csv/#notes carefully.

You need to consider the field `num_cases` to get the number of cases each row of data represents.
