### ISSUE TITLE
contradiction in state_test_data.json

### ISSUE THREAD

**Issue by KMuthusamyms** [covid19india/api#333]
In State_test_data.json, there are contradictions in the number of negative, positive, and total tested.
Data in the API is different from the source which has mentioned.

`{
			"coronaenquirycalls": "",
			"cumulativepeopleinquarantine": "",
			"negative": "550643",
			"numcallsstatehelpline": "",
			"numicubeds": "",
			"numisolationbeds": "",
			"numventilators": "",
			"populationncp2019projection": "",
			"positive": "30152",
			"source1": "https://stopcorona.tn.gov.in/wp-content/uploads/2020/03/Media-Bulletin-06.06.2020.pdf",
			"source2": "",
			"state": "Tamil Nadu",
			"tagpeopleinquarantine": "",
			"tagtotaltested": "Samples Sent",
			"testpositivityrate": "",
			"testspermillion": "",
			"testsperpositivecase": "",
			"testsperthousand": "",
			"totaln95masks": "",
			"totalpeoplecurrentlyinquarantine": "",
			"totalpeoplereleasedfromquarantine": "",
			"totalppe": "",
			"totaltested": "576695",
			"unconfirmed": "",
			"updatedon": "06/06/2020"
		},`
Here mentioned totaltested as 576695 and positive as 30152.
so the negative should be 546543. but here mentioned that negative as 550643.
The data may have been entered incorrectly. 
The mentioned source is correct.
I suggest another one source as [https://nhmtn.maps.arcgis.com/apps/opsdashboard/index.html#/095ad0a1c0254b058fa36b32d1ab1977](url)

**Comment by sudevschiz** [comment]
Isn't this in line with what was mentioned in the bulletin?
![image](https://user-images.githubusercontent.com/4298868/83996361-e9262080-a996-11ea-999d-d4bacf961357.png)


Not sure why the discrepancy. Will forward to the necessary team

**Comment by KMuthusamyms** [comment]
> Isn't this in line with what was mentioned in the bulletin?
> ![image](https://user-images.githubusercontent.com/4298868/83996361-e9262080-a996-11ea-999d-d4bacf961357.png)
> 
> Not sure why the discrepancy. Will forward to the necessary team

Okay @sudevschiz 
Thank you for your reply.

**Comment by sudevschiz** [comment]
Closing.
