### ISSUE TITLE
`totaltested` on latest update is empty for some states

### ISSUE THREAD

**Issue by gurrrung** [covid19india/api#344]
`totaltested` of latest date to fetch the total tests conducted in a state. But now it is empty for some stats like Punjab, Haryana.

https://api.covid19india.org/state_test_data.json
Check `"updatedon": "12/06/2020"`.

**Comment by sudevschiz** [comment]
Checked for Punjab for 12/06/2020, looks good now. Could've been a temporary miss.

However, please don't expect testing data to be available for all states on all days. Some days, the states doesn't report it.
