### ISSUE TITLE
[API] Real-time MoHFW Scraper

### ISSUE THREAD

**Issue by parshnt** [covid19india/api#345]
I've developed an API that scrapes data from [MoHFW](https://www.mohfw.gov.in/) and serves the data on a JSON endpoint. The data is scraped and served in real-time.

- Deployed on Cloudflare Workers
- Under 2ms response time
- can serve up to 100k requests/day

**API**

https://mohfw.covid19in.workers.dev/

@JunaidBabu, Please let me know if I can add this to README document under Alternate API's

Also, It can help with workflows, like verifying each state's numbers when the dashboard is updated and so on.

**Comment by sudevschiz** [comment]
Scope of the alternate API is to list the endpoints that represents the same that we have collected in the Google Sheet in a different way or through a different tech.

MoHFW API is irrelevant in this case. Thanks you!
