### ISSUE TITLE
Data is inconsistent with the State Bulletin

### ISSUE THREAD

**Issue by aosaslam** [covid19india/api#346]
Firstly huge thanks to you all. 
As said in the site, the data is sourced from official sources. A tiny concern here is please validate it before/after uploading it, as the numbers don't match. Please find the screenshot below and compare it the data being displayed. 

Also, if you could provide a screen for uploading queries/corrections/suggestions on the portal itself you could reach out to more people. 

![Screenshot_2020_0613_012125](https://user-images.githubusercontent.com/20989739/84541099-4d890d00-ad14-11ea-8fdf-fecbe02bb913.jpg)

**Comment by sudevschiz** [comment]
This is the data for Telangana in the site for June 12th. Could you tell us where the error is?
![image](https://user-images.githubusercontent.com/4298868/84685599-84aa2900-af75-11ea-8533-819198ec1f23.png)
