### ISSUE TITLE
Add state-wise api for State -Confirmed-Recovered-Deaths-Active

### ISSUE THREAD

**Issue by Satyampd** [covid19india/api#35]
There is no api for Statewise data, can that api added for state-wise data of Confirmed-Recovered-Deaths-Active.

**Comment by amodm** [comment]
https://api.rootnet.in/covid19-in/unofficial/covid19india.org/statewise

https://api.rootnet.in/covid19-in/unofficial/covid19india.org/statewise/history

**Comment by Satyampd** [comment]
Okay thanks, closing it!
