### ISSUE TITLE
Consider releasing data under CC-BY-SA license

### ISSUE THREAD

**Issue by asdofindia** [covid19india/api#357]
Currently it is unclear what license the data is released under. The existence of a public API means that the team wants others to use the data. But not knowing what license the data comes in makes it difficult for others to use the same.

I suggest that the license under which the dataset is released be documented clearly.

I would say use CC-BY-SA, but there are other possible licenses documented here: https://help.data.world/hc/en-us/articles/115006114287-Common-license-types-for-datasets

**Comment by asdofindia** [comment]
Regarding the GPL license, https://asd.learnlearn.in/gpl-api-output/

**Comment by sudevschiz** [comment]
@asdofindia Thanks for raising this issue. Yes, we have been pondering over the correct licensing format for the data. The link you shared should be helpful.

cc @triedcatched

**Comment by naveenpf** [comment]
Open Data Commons Open Database License
https://opendatacommons.org/licenses/odbl/index.html

**Comment by themonk911** [comment]
+1 we're looking at using this data in open-covid-19 (https://github.com/open-covid-19/data), but cannot do so until the licensing is clear.

**Comment by naveenpf** [comment]
@themonk911 some #opendata govt of India is releasing. 
https://data.gov.in/major-indicator/covid-19-india-data-source-mohfw

**Comment by themonk911** [comment]
Thanks @naveenpf, unfortunately it doesn't look like they provide historical data. Do you know if any other source provides historical data?

**Comment by naveenpf** [comment]
@themonk911 Wikidata https://www.wikidata.org/wiki/Wikidata:WikiProject_India/COVID-19_task_force

**Comment by themonk911** [comment]
Thanks @naveenpf, that's really useful :)

**Comment by sudevschiz** [comment]
I have split the License of the repository into two - one for code and one for the data. Both are listed separately in two different files.
https://github.com/covid19india/api/blob/master/LICENSE_DATA
https://github.com/covid19india/api/blob/master/LICENSE_CODE


Shifted from GPL3.0 to MIT for the codebase to make things more permissive. Will send out a communication regarding this in the dev group

@themonk911 @asdofindia, hope this clears the licensing situation.

**Comment by themonk911** [comment]
Thanks so much!
