### ISSUE TITLE
Getting negative data in districtwise

### ISSUE THREAD

**Issue by Ayush-Walia** [covid19india/api#359]
Some values are showing -ve data, in 
https://api.covid19india.org/state_district_wise.json https://api.covid19india.org/v2/state_district_wise.json

Ex: 
{
        "district": "Unknown",
        "notes": "",
        "active": -1159,
        "confirmed": 1179,
        "deceased": 4,
        "recovered": 2331,
        "delta": {
          "confirmed": 0,
          "deceased": 0,
          "recovered": 0
        }
      }
Here active cases is negative.

![Screenshot from 2020-06-21 13-16-32](https://user-images.githubusercontent.com/16828403/85219471-a5cda800-b3c1-11ea-8249-bff6a2cc2d95.png)

Here active cases is -9

**Comment by sudevschiz** [comment]
This means that **know** that there are 10 recovery in some unknown districts, and 1 unknown district confirmed case. The active is negative here because only then the total active for the state would look correct.
