### ISSUE TITLE
v3 timeseries api link is not working

### ISSUE THREAD

**Issue by aberrantdoc** [covid19india/api#362]
The api at the following link is showing a 404 error. 
https://api.covid19india.org/v3/data-%7BYYYY-MM-DD%7D.json

![image](https://user-images.githubusercontent.com/63073968/85222212-10d5a980-b3d7-11ea-93a4-0c092a4503fc.png)

**Comment by JunaidBabu** [comment]
Try something like https://api.covid19india.org/v3/data-2020-06-20.json

**Comment by aberrantdoc** [comment]
Oh didnt realise there is a separate json for each day. Thank you.
