### ISSUE TITLE
state names in gender field 

### ISSUE THREAD

**Issue by vamshi9666** [covid19india/api#37]
I was visualizing data and found a blunder in raw data. Gender field has state names in it

**Comment by vamshi9666** [comment]
graph :
<img width="1370" alt="Screenshot 2020-03-30 at 3 25 40 PM" src="https://user-images.githubusercontent.com/28837336/77899955-f3db7f80-729a-11ea-85c9-890c30f46dd2.png">

**Comment by vamshi9666** [comment]
@JunaidBabu  is this acknowledged and resolved already?

**Comment by vamshi9666** [comment]
#39

**Comment by sudevschiz** [comment]
Hi @vamshi9666 , I am not able to reproduce this. The gender column seem to have only M and F values
```
import requests
import pandas as pd
r = requests.get("https://api.covid19india.org/raw_data.json")
pdb = r.json()

df = pd.DataFrame.from_dict(pdb['raw_data'])
df.gender.value_counts()
```

```
     728
M    389
F    188
Name: gender, dtype: int64

```
