### ISSUE TITLE
isn't this \n in `phonenumber` unnecessary?

### ISSUE THREAD

**Issue by gurrrung** [covid19india/api#373]
API: https://api.covid19india.org/resources/resources.json

![Screenshot from 2020-06-28 18-28-28](https://user-images.githubusercontent.com/30543444/85948217-37fb2080-b96d-11ea-8857-7926afb203c8.png)

**Comment by sudevschiz** [comment]
Yes, this was necessary to display in the website. However, not we have deprecated the resources tab and this json won't be updated further.
