### ISSUE TITLE
Date format error in data on covid19 statewise_tested_numbers_data.csv

### ISSUE THREAD

**Issue by ashokrupana** [covid19india/api#379]
Date format error in data on covid19 statewise_tested_numbers_data.csv as for many rows date and months are swapped its is showing incorrect date. it is may be because people are using different format when submitting the data i.e. dd/mm/yyyy instead of mm/dd/yyyy.

**Comment by shuklaayush** [comment]
Can you give examples of specific entries?. [Here's](https://github.com/covid19india/api/blob/gh-pages/csv/latest/statewise_tested_numbers_data.csv) the file
