### ISSUE TITLE
I have created a Karnataka specific site.

### ISSUE THREAD

**Issue by Karthikb777** [covid19india/api#380]
I have created a react site for Karnataka state using covid19india APIs. Here is the site: https://karthikb777.github.io/covid19karnataka/

Here is the repo: https://github.com/Karthikb777/covid19karnataka

**Comment by sudevschiz** [comment]
Thanks for using the data. Earlier we used to add derivative projects in our README. However, we have stopped the process as we couldn't do justice to all the work. 
Closing this issue as there is no more action here. Thank you.
