### ISSUE TITLE
Testing data missing from data-all.json

### ISSUE THREAD

**Issue by AnkitGoyal430** [covid19india/api#381]
I have noticed testing data to be missing for some states from data-all response from https://api.covid19india.org/v3/data-all.json

This is mostly for states for which district level info on testing is available, total testing info has been removed. Is there some change in formats in data-all?
Even on state dashboard "https://www.covid19india.org/state/MH" it now does not show testing info properly for states.

**Comment by shuklaayush** [comment]
Seems to be there for me. Can you give a more specific example?
![image](https://user-images.githubusercontent.com/27727946/86509707-90b43880-be07-11ea-8485-ebbab4be8180.png)
![image](https://user-images.githubusercontent.com/27727946/86509727-a75a8f80-be07-11ea-919f-38486002f72b.png)

**Comment by AnkitGoyal430** [comment]
Its seem to be fixed now :|. 
In the morning i was not getting the data for Maharashtra, among other states.
Even on state dashboard page("https://www.covid19india.org/state/MH") no of tests were showing to be 0 for all days in graph.

**Comment by shuklaayush** [comment]
Might've been a temporary issue
