### ISSUE TITLE
Bug in district test data

### ISSUE THREAD

**Issue by john2014** [covid19india/api#382]
Here are following bugs in district test data file:

1. In this link https://github.com/covid19india/api/tree/gh-pages, there are three similar files: (a) district_test_data.json (b) district_testing.json and (c) district_testing_data.json 

Which one is the correct one? Also why are there three files with same data?

2. Currently only district_testing_data.json  is been updated daily. The other two files havent been updated in more than 9 days. Should all three files be updated (if they are different)?

3. The content of district_testing_data.json  is not jumbled up. There are lots of keys with random words (instead of specific words like tested, source1, etc).

4. The tested and confirmed value in "state test data" and "district test data" file for a particular date (eg total tests and total positive value) do not match the total tests and confirmed valued for particular data file (eg /v3/data-2020-06-03.json).

**Comment by sudevschiz** [comment]
Thanks for notifying. @JunaidBabu can we do a cleanup and do a force push?

**Comment by JunaidBabu** [comment]
Removed outdated testing data files.
Kept only district_testing_data.json in gh-pages.
