### ISSUE TITLE
States Daily confirmed value is inaccurate 

### ISSUE THREAD

**Issue by john2014** [covid19india/api#383]
The values in this file https://github.com/covid19india/api/blob/gh-pages/states_daily_csv/confirmed.csv is not accurate.

If you scroll down to last row, and see total, it says 22718.

This means total confirmed cases for all states is only 22,718. This confirmed value is not accurate.

**Comment by shuklaayush** [comment]
It's that particular dates' all-India confirmed count (number of new cases added today). Like for today right now
![image](https://user-images.githubusercontent.com/27727946/86519731-612f1b80-be5b-11ea-9c57-a257927bcba6.png)
