### ISSUE TITLE
Different files have different values for confirmed cases

### ISSUE THREAD

**Issue by john2014** [covid19india/api#384]
Daily File: If you look at file https://api.covid19india.org/v3/data-2020-07-04.json, the confirmed cases for Maharashtra state is 200064 for July 4

State test data: If you look at file https://api.covid19india.org/state_test_data.json, for date July 4, the confirmed cases for Maharashtra is 203816.

Expected: Both of these files should have same values.

**Comment by sudevschiz** [comment]
No, such parity is not expected. Cases data is collected from the bulletin and the testing data is collected from MEDD report. Depending on when the release the bulletin and what is the daily cut-off that is considered, the numbers would differ. Information of positives in test data is collected as-is present in the testing related press release.

**Comment by shuklaayush** [comment]
Just to add, the testing data reports the number of postive **samples** and not people. It's anyone's guess as to whether that's an important distinction

**Comment by john2014** [comment]
So when the data says total cases confirmed, does it actually mean total samples confirmed? Hence this is definitely an important distinction.

PS: Few months back I read that two samples are collected per person.

**Comment by shuklaayush** [comment]
Nope, I think when it comes to Confirmed/Recovered/Deceased counts, the data is reported in terms of the number of people. The positive samples data is only present in the state test data/district test data files, and at least not used anywhere in the v3 APIs
