### ISSUE TITLE
Older files are been updated frequently

### ISSUE THREAD

**Issue by john2014** [covid19india/api#385]
If you look at the folder: https://github.com/covid19india/api/tree/gh-pages/v3, the last updated date for most files is around 10 hours ago. These older files should not be updated.

If you look at history for July 29 file, https://github.com/covid19india/api/commits/gh-pages/v3/data-2020-06-29.json, you would see that it been updated a lot of times.

**Comment by sudevschiz** [comment]
@shuklaayush  We make corrections for previous dates when new information is available regarding some case. But is the code logic updating all the files in every run?

**Comment by JunaidBabu** [comment]
Sometimes data in sheets are updated for previous dates. This is the reason why older files are getting updated.
