### ISSUE TITLE
A search engine based on your APIs indexing daily covid-19 related data

### ISSUE THREAD

**Issue by feast0101** [covid19india/api#390]
Hi Team,

First of all, I would like to appreciate your effort for providing accurate data about covid-19 situation in India on real time basis. Considering India's widely diversified source and formats it's really a herculean task by any measure.
I am a software engineer by profession and thought to contribute to your effort in my own way. 
Here are details:

I have created a search engine based on your APIs indexing daily covid-19 related data of all Indian states/UT. It bootstraps latest collection of data from https://api.covid19india.org/ endpoints. It has a feature to daily index updated data (cron job).

Git URL:
[https://github.com/feast0101/COVID19India-SearchEngine](https://github.com/feast0101/COVID19India-SearchEngine)

If you find it interesting, do let me know.
It will further motivate me to do interesting stuff with the data you are collecting.

Regards,
KD

**Comment by sudevschiz** [comment]
Hey interesting work! Unsure what is the use-case of the search engine. Please do share.
Nonetheless, great effort.

**Comment by feast0101** [comment]
**Use Case 1:** One single API with uniform format instead of 8 different datasets being served by 8 separate API endpoints.
Also because of the Solr/Lucene platform, it brings on the table some of the advanced search related features like: 

- Advanced full-text search capability
- Sorting, Filitering, Ordering
- Faceted search
- Inbuilt spelling check
- Performance improvement as it is ideal for handling big data 
- Rich in document parsing
- Highly scalable and fault tolerant

**Use Case 2:** Zero maintenance effort required, as we can automate daily index/update activity as a cron job 

**Use Case 3:** Enrich response data set by combining multiple Solr collections containing various data sets. Custom request handler is another option in this regard.

High Level DFD:

<img width="800" alt="Screenshot 2020-07-12 at 10 19 26 PM" src="https://user-images.githubusercontent.com/6492003/87252420-87bf0900-c490-11ea-8f0d-f12874f5b5e4.png">

**Comment by feast0101** [comment]
For demo purpose, I have deployed the search engine on Google Cloud :

**Dashboard Link:**
https://covidservice-axuikumjgq-uc.a.run.app/solr/#/covid19/query)

**Total Number of Recovered Cases (stats. stats_fields. numcases.sum)**
https://covidservice-axuikumjgq-uc.a.run.app/solr/covid19/select?fq=currentstatus%20%3A%20%22Recovered%22&q=*%3A*&rows=0&stats.field=numcases&stats=true

**Total Number of Hospitalised Cases (stats. stats_fields. numcases.sum)**
https://covidservice-axuikumjgq-uc.a.run.app/solr/covid19/select?fq=currentstatus%20%3A%20%22Hospitalized%22&q=*%3A*&rows=0&stats.field=numcases&stats=true

**Total Number of Fatalities (stats. stats_fields. numcases.sum)**
https://covidservice-axuikumjgq-uc.a.run.app/solr/covid19/select?fq=currentstatus%20%3A%20%22Deceased%22&q=*%3A*&rows=0&stats.field=numcases&stats=true

Let me know if any info required related to the search queries.

**Comment by sudevschiz** [comment]
@feast0101 This is great work, however the functionality to query by date is provided in the v4 endpoints. Please to feel free to maintain the ETL process and search engine if you or others find it useful for any of your work. 

Closing this issue from the repo as there is no more action.
