### ISSUE TITLE
Data issue: Invalid character '+' in state_test_data.json

### ISSUE THREAD

**Issue by jobyj0101** [covid19india/api#392]
In state_test_data.json, there is an entry with "negative": "1210+". Could you please remove the + from it.

Problem entry:
"state": "Andaman and Nicobar Islands"
"updatedon": "17/04/2020"
"negative": "1210+"

Thanks,

**Comment by sudevschiz** [comment]
Thanks for reporting. It was an inadvertent error. Have fixed it now.
