### ISSUE TITLE
Total values in new update

### ISSUE THREAD

**Issue by PinkyPao** [covid19india/api#394]
Hello everyone, 

I used to work with your data since March creating the day cumulative cases total, by adding the "Num Cases" variable for each csv. However, on the last update of 12 July 2020 the sum of num cases is no longer reflecting the reality of the total number of cases and the documentation is not clear. Can you please help me with this? 

Thanks in advance

**Comment by bee-rickey** [comment]
@PinkyPao can you please provide an example?

**Comment by PinkyPao** [comment]
I think I figured out the problem. This link: https://api.covid19india.org/csv/latest/raw_data.csv used to provide information from partitions 1 and 2 (from January to April 26th)- as stated by the documents. But now, somehow it has from other dates. When you changed the information in this link, so it changed the counts. 

Thanks!

**Comment by sudevschiz** [comment]
Hi,
Please don't use the raw_data.csv. It's not officially supported right now. We are working on making a singular raw_data that would fix lot of format inconsistencies across sheets. Will publish it once it's verified to be correct.

Outright, try not to use raw_data if you are looking for aggregated numbers. Use the files data in v4/ folder of gh-pages branch for that.

If you need to do patient level analysis, please use the individual raw data files for now.
