### ISSUE TITLE
districts_daily.Json file data update issue

### ISSUE THREAD

**Issue by Sudhak84** [covid19india/api#396]
Data is updated only till 12th Jul 2020. Please check. I have checked it on 15th Jul 2020. 

https://api.covid19india.org/districts_daily.json

**Comment by aravindpanil** [comment]
districts_daily stopped generating data after 12th July. However, the page was still available until yesterday. Now it just gives a **404**. Did something change?

**Comment by JunaidBabu** [comment]
Kindly refer to the discussion in #393
