### ISSUE TITLE
[Feature Addition] District coordinates

### ISSUE THREAD

**Issue by parshnt** [covid19india/api#399]
Hi,

can we add Latitude & Longitude field with the district_list.csv file, it'll help users in plotting the cases, etc. 
I've made a [CSV](https://parshnt.me/district-geocodes-IN/coordinates.csv) from geoPy that can be used for this.

Thanks

**Comment by parshnt** [comment]
update: Here is the [code](https://github.com/parshnt/district-geocodes-IN/blob/master/source.ipynb) I used to get the lats & long for the district.

You can integrate this into the parser to merge the coordinates into the latest district list.

thanks

**Comment by JunaidBabu** [comment]
A very detailed map of India is available here
 https://github.com/covid19india/covid19india-react/tree/master/public/maps

**Comment by parshnt** [comment]
Thanks a lot, will surely check this out.
But, my specific use case requires the use of lats & longs, hence the issue.
