### ISSUE TITLE
how to fix typos in data?

### ISSUE THREAD

**Issue by imbdb** [covid19india/api#40]

**Comment by dhruvdutt** [comment]
I think you can't. There's a dedicated data team which maintains all the data in Google Sheet.
Probably, we'll have to put requests somewhere/here for them to fix things.

**Comment by imbdb** [comment]
We should have automated validation system which validates simple typos and restricts user from doing simple mistakes.
I can do that if possible.

**Comment by sudevschiz** [comment]
What typos? Could you describe further?

**Comment by alphasingh** [comment]
@sudevschiz Some of the points had been mentioned already in #31 #26 and #29

**Comment by JunaidBabu** [comment]
> 
> 
> @sudevschiz Some of the points had been mentioned already in #31 #26 and #29

@alphasingh, we've fixed the names in sheet as well as the site to match correctly. Could you please check whether these issues still exist? If yes could you close them from this repo and raise at https://github.com/covid19india/covid19india-react ?
