### ISSUE TITLE
flaw in https://api.covid19india.org/csv/latest/district_wise.csv

### ISSUE THREAD

**Issue by tobymammen** [covid19india/api#403]
Hi,

There is apparently a flaw in the above mentioned file.

The data related to Andamans and Nicobar Islands has been unchanged since at least 1st July. The numbers are the same since. When crosschecked with other district level datafiles, this discrepancy was noticed.

Hope this will be checked and rectified at the earliest.

Regards

**Comment by sudevschiz** [comment]
Andaman Nicobar Islands do not provide districtwise case details. We used to capture it till July 1st with whatever information we could gather from local media and tweets. However, as the case numbers increased and we did not have an anchor on how many cases are present in each district, we have stopped updating the district numbers for AN Islands.

**Comment by tobymammen** [comment]
Thanks for your prompt reply.
