### ISSUE TITLE
Cumulative data is one day old with this API https://api.covid19india.org/data.json

### ISSUE THREAD

**Issue by Abhishek-Srivastava** [covid19india/api#405]
![image](https://user-images.githubusercontent.com/2565995/88565532-5e86a700-d052-11ea-9562-cb0739fe59c5.png)

However the website shows:
![image](https://user-images.githubusercontent.com/2565995/88565583-72320d80-d052-11ea-9526-e150b074e75c.png)

**Comment by VinitSawant09** [comment]
You ll have to loop through the state-wise attribute and get cumulative results
