### ISSUE TITLE
Cannot select 27 july date

### ISSUE THREAD

**Issue by nitin065** [covid19india/api#406]
Cannot select 27th July date. When selected fall back to today's data.

**Comment by sudevschiz** [comment]
Where? Which endpoint?

**Comment by nitin065** [comment]
> Where? Which endpoint?

From UI page. At least from mobile.

**Comment by sudevschiz** [comment]
![image](https://user-images.githubusercontent.com/4298868/88833838-e1a02c80-d20d-11ea-841d-696e9150b27e.png)
Looks perfectly fine at my end. Could you try again?

**Comment by nitin065** [comment]
> ![image](https://user-images.githubusercontent.com/4298868/88833838-e1a02c80-d20d-11ea-841d-696e9150b27e.png)
> Looks perfectly fine at my end. Could you try again?

Yes, someone might have fixed it. 
Closing now!!
