### ISSUE TITLE
Google sheet can't fetch District level data due to size limit

### ISSUE THREAD

**Issue by vishalgodha** [covid19india/api#407]
https://api.covid19india.org/csv/latest/districts.csv

Google sheets can't fetch data with IMPORTDATA formula. Need to split CSV data.

Here is Error screenshot -
![Screenshot_20200729-223754_Sheets](https://user-images.githubusercontent.com/68960923/88830969-4fd3f780-d1ec-11ea-9ac3-e87e39621f57.jpg)

**Comment by sudevschiz** [comment]
This time-series data is bound to grow. Right now we have no plans to split it into parts.
Instead of using `IMPORTDATA` function, there could be custom scripts that can handle larger input sizes. Could you please search for those?
