### ISSUE TITLE
Typo in Ahmedabad

### ISSUE THREAD

**Issue by dhruvdutt** [covid19india/api#41]
There's a typo in [Gujarat - Ahmedabad](https://en.wikipedia.org/wiki/Ahmedabad)

Please tag the relevant people from data team to fix in Sheets DB.

![image](https://user-images.githubusercontent.com/5961873/77923421-103de300-72c0-11ea-8793-6bd33c32f86b.png)

**Comment by manojkumarsmks** [comment]
This could be a good start for me, Can I work on this ?

**Comment by circuitmamu** [comment]
#51 also look I found another 2 typos

**Comment by JunaidBabu** [comment]
https://github.com/covid19india/api/issues/51#issuecomment-607166974
