### ISSUE TITLE
Exact time of update

### ISSUE THREAD

**Issue by DnanaDev** [covid19india/api#411]
I'm creating a data pipeline with data from multiple sources. To keep the data consistent I plan to schedule the cron jobs to fetch data after each source updates.
I couldn't find the exact time of update for the following two sources from the documentation :

1. National Level :Time series, State-wise stats and Test counts (JSON) | https://api.covid19india.org/data.json
2. state_wise_daily (CSV)| https://api.covid19india.org/csv/latest/state_wise_daily.csv

@JunaidBabu, @sudevschiz Would appreciate some help.

**Comment by bee-rickey** [comment]
@DnanaDev I don't think it would be possible to get the exact update time of either of the two files. They get updated throughout the day and the only way to get that info would be to either add that timestamp in the file (not feasible) or to take it from the git repo.

**Comment by DnanaDev** [comment]
@bee-rickey Okay, thanks for the info. Just to be clear I was looking the time the entry for the previous day is created. I've sometimes seen it get created 30mins after midnight, sometimes not even by 02:00 (like yesterday). 
If that's not feasible feel free to close the issue. I'm currently testing the ingestion process at 5 in the morning.

**Comment by sudevschiz** [comment]
@DnanaDev The cron job that adds the total cases for the previous day into those endpoints runs around 30 mins before midnight. However, yesterday, for some reason the trigger did not run. It was updated in the morning after we realized the same.

You can continue to expect the data to be updated around midnight.

**Comment by DnanaDev** [comment]
@sudevschiz @bee-rickey Cool, thanks for helping out.
