### ISSUE TITLE
Approximate Lat/Long storage in Patient's Data.

### ISSUE THREAD

**Issue by maverick9122** [covid19india/api#428]
Current JSON Schema for Patient's Data
```
{
			"agebracket": "",
			"contractedfromwhichpatientsuspected": "",
			"currentstatus": "Hospitalized",
			"dateannounced": "22/09/2020",
			"detectedcity": "",
			"detecteddistrict": "Aizawl",
			"detectedstate": "Mizoram",
			"entryid": "297549",
			"gender": "",
			"nationality": "",
			"notes": "",
			"numcases": "107",
			"patientnumber": "",
			"source1": "http://twitter.com/dipr_mizoram/status/1308217294968020993",
			"source2": "",
			"source3": "",
			"statecode": "MZ",
			"statepatientnumber": "",
			"statuschangedate": "",
			"typeoftransmission": ""
		},
```
**Suggestion:**
Store aproximate lat/long of each patient, it will add up in below features.
Mapping patients count on exact locations of Map based on Lat/Long
Alarming User if he is entering in a zone having high number of Patients (Red Zone)
Find of no infected patients in a local area.

**Comment by bee-rickey** [comment]
The data being released now is mostly aggregated at district level. With no area based information, lat-long adds little value since districts are geographically big and the lat-long for districts can be derived easily outside the api.

**Comment by maverick9122** [comment]
closing this issue,
as LAT and LONG can be calculated from Google's location API passing address as parameter.

```
URL url = new URL(
                "http://maps.googleapis.com/maps/api/geocode/json?address="
                        + URIUtil.encodeQuery("Sayaji Hotel, Near balewadi stadium, pune") + "&sensor=true");
```
