### ISSUE TITLE
Data undefined in "state_test_data" ?

### ISSUE THREAD

**Issue by the-wrong-guy** [covid19india/api#431]
The `testsperthousand` and `testpositivityrate` got undefined which was working yesterday

Please look at this issue asap

**Comment by sky-megh** [comment]
We're facing the same issue! Is there a particular reason why these variables have been discontinued?

**Comment by the-wrong-guy** [comment]
> We're facing the same issue! Is there a particular reason why these variables have been discontinued?

Well Idk, they have changed some their urls too I guess

**Comment by sudevschiz** [comment]
@the-wrong-guy thanks for reporting the issue. Could you post the endpoint that you are using?

**Comment by sudevschiz** [comment]
@the-wrong-guy @sky-megh  These fields have not been updated for long. It's better if you calculate the testpositivity rate at your end from the cases and the tests conducted. 

Also, you can get the state and district population that we are using from : https://api.covid19india.org/misc.json

**Comment by the-wrong-guy** [comment]
> @the-wrong-guy @sky-megh These fields have not been updated for long. It's better if you calculate the testpositivity rate at your end from the cases and the tests conducted.
> 
> Also, you can get the state and district population that we are using from : https://api.covid19india.org/misc.json

Well I have little confusion on which particular end point the error is happening cause while in my app I am getting different data but again testing in Postman I am getting different set of data. So again I will check and let you know soon
