### ISSUE TITLE
District wise data for some more states

### ISSUE THREAD

**Issue by sanyam-git** [covid19india/api#433]
The website says that the state bulletin does not provide district wise data for Assam and Telangana. (same display as below for Telangana)
![assam](https://user-images.githubusercontent.com/43791665/97069011-82726e00-15ea-11eb-85d8-273e4c484fef.png)

The data can be found here :
* **Assam** : https://covid19.assam.gov.in/all-districts/. (official website by Government of Assam)
* **Telangana** : https://www.bing.com/covid/local/telangana_india?vert=graph (bing's corona tracker. They did not provide any primary source, but can be relied upon. Maybe they are taking the cumulative sum of daily media bulletins by Government of Telangana)

These two are major states of India and should be added as soon as possible.
I would be glad to help, if someone can guide a bit about where to get started and what all to do, to add the following states.

**Comment by sanyam-git** [comment]
moved from [here](https://github.com/covid19india/covid19india-react/issues/2379) as [suggested](https://github.com/covid19india/covid19india-react/issues/2379#issuecomment-715882706) by @shuklaayush. Tagging @bee-rickey and @sudevschiz.

**Comment by bee-rickey** [comment]
@sanyam-git If I'm not wrong, that dashboard hasn't been updated in a very very long time. So can't really use that dashboard for any updates.

**Comment by sanyam-git** [comment]
@bee-rickey  Thanks for the clarification for both the states.
