### ISSUE TITLE
Incorrect value for Date_YMD column in 'state_wise_daily' csv file 19-Oct-2020 onwards

### ISSUE THREAD

**Issue by danishali1511** [covid19india/api#434]
Hey Guys,

Just downloaded this .csv file 'state_wise_daily' from 'https://api.covid19india.org/csv/latest/state_wise_daily.csv' and noticed that date values for column **Date_YMD** are repeating 19-Oct-2020 onwards so thought of bringing into notice to you guys.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/60676555/97115842-337a2500-171f-11eb-843a-a7b791e10386.png">

**Comment by sudevschiz** [comment]
@danishali1511 Thanks for notifying the error. I have fixed the date_YMD column now. It happened due a missing formula in sheets.
