### ISSUE TITLE
Inaccurate count of Recovered in the state Tamilnadu

### ISSUE THREAD

**Issue by tamilanmanikandan** [covid19india/api#44]
The tracker shows Actual Recovered  people are 4 in TamilNadu but raw_data API returns '2' instead.

**Comment by krishnasen2401** [comment]
it seems the data api which used by the main website has data entered manually so it would be different

**Comment by sudevschiz** [comment]
Raw data cannot be used for computing the recovered cases.

Work on https://github.com/covid19india/api/issues/68 will fix this issue.
