### ISSUE TITLE
Data incorrect

### ISSUE THREAD

**Issue by kaiser101** [covid19india/api#443]
Looking at the figures for Maharashtra yesterday i.e. 2 December 2020, the numbers dont add up
Overall Maharashtra new cases - 3350 (Almost all the major news sites confirm the number of new cases to be 5600)
However if you add up all the new cases for the individual districts, the number is much more than 3350. In fact it is close to 6000. So you need to check your sources again.
![covid19org](https://user-images.githubusercontent.com/1123273/100960748-ecb1f300-3546-11eb-9422-ac0efa4335f3.png)

**Comment by bee-rickey** [comment]
We are in line with the bulletin. MH bulletin has backdated cases added yesterday.
