### ISSUE TITLE
Incorrect update date for Ladakh in states test data

### ISSUE THREAD

**Issue by jishnub** [covid19india/api#450]
In state test data, entry 4892 and 4893 for Ladakh point to the same facebook link as their source, but have different update dates (4892 has 22/1/2021 while 4893 has 24/1/2021). The update in the link is however on 08/10/2020. Should this date be the value of `updateon`?

**Comment by sudevschiz** [comment]
Thanks for reporting. The link in source3 was incorrect.
It's better to use source1 as that's the most relevant source.
