### ISSUE TITLE
West Bengal data stopped updating after 1st Feb

### ISSUE THREAD

**Issue by amritb** [covid19india/api#456]
Hi,

Is there a new version for data-all.json ? I was using https://api.covid19india.org/v4/data-all.json but from 1st of Feb it's not being updated. The source have new data though https://www.wbhealth.gov.in/pages/corona/bulletin

Is there a new API for this? Or the google spreadsheet (I couldn't find/view it) is not updated anymore for WB ? Let me know if I can personally update the sheets for WB somewhere.

Thanks for this awesome project!

**Comment by shuklaayush** [comment]
Hey @amritb, we ran into some space issues with GitHub and `v4/data-all.json`. Hence, we deprecated the unminified version. Please use https://api.covid19india.org/v4/min/data-all.min.json. It's the same file, just smaller.
