### ISSUE TITLE
warn people via banner to use `pmcares@sbi` instead of `pmcare@sbi` which is a fraud UPI

### ISSUE THREAD

**Issue by deep5050** [covid19india/api#46]
according to wikipedia (https://en.wikipedia.org/wiki/PM_CARES_Fund):
"While the original UPI account was PMCARES@SBI, Delhi Police booked unknown individuals for creating an account removing the 'S', PMCARE@SBI, intended to scam people."

**Comment by sudevschiz** [comment]
Out of scope.
