### ISSUE TITLE
icmr_testing_details not updated

### ISSUE THREAD

**Issue by shyam2520** [covid19india/api#460]
the total positive sample column has been null for 80% of the dates , would you be able to fix it ?

**Comment by ShikariShambuJr** [comment]
HI which sheet and column are you referring to?

**Comment by shyam2520** [comment]
tested_numbers_icmr_data : https://api.covid19india.org/csv/latest/tested_numbers_icmr_data.csv

statewise_tested_numbers_data : https://api.covid19india.org/csv/latest/statewise_tested_numbers_data.csv

in both these files total positive samples data columns has a lot of empty data

**Comment by sudevschiz** [comment]
Hi @shyam2520,
In the early days, ICMR used to publish the total positive cases in their daily bulletin. However, they stopped providing that data point after a few weeks. 

That's the reason for this column to be null. 
Please refer to the other api endpoints for this data point.

**Comment by shyam2520** [comment]
okay thank you
