### ISSUE TITLE
How to use these links as json?

### ISSUE THREAD

**Issue by Aakashmangla2000** [covid19india/api#465]
http://api.covid19india.org/csv/latest/vaccine_doses_statewise.csv
http://api.covid19india.org/csv/latest/cowin_vaccine_data_statewise.csv

How do I use these links in my website as i have previously used "https://api.covid19india.org/data.json" which easily gives me json data, how can I get same links for this csv data in json format?

**Comment by shreyanshxyz** [comment]
I want to know this as well! Following

**Comment by harsshjain** [comment]
Check this out! https://api.covid19india.org/documentation

**Comment by swarooprooney** [comment]
https://api.covid19india.org/states_daily.json
