### ISSUE TITLE
Will the vaccinated CSV format change again?

### ISSUE THREAD

**Issue by gouenji-shuuya** [covid19india/api#466]
The `vaccine_doses_administered_statewise` changed yesterday.

I want to know would it change again in the coming future? Because I would need to do changes to my program when they happen.

Also, why are the stats one day late nowadays on the API, but not on the website?

**Comment by ShikariShambuJr** [comment]
Hi the changes were made to accommodate the new data i.e the breakup of doses statewise and reflect the same on website in coming days.We would try our best not to change it again.

Regarding the date the data released on 27th April'21 is for 26th April'21.

If you have any more things to ask please message here.
