### ISSUE TITLE
Mismatch between MoHFW numbers and the vaccination CSV data

### ISSUE THREAD

**Issue by siddhpant** [covid19india/api#473]
For today, MoHFW on it's website shows the following:

![image](https://user-images.githubusercontent.com/25429745/117564121-0f34d300-b0c8-11eb-9902-2b66a1f2c432.png)

Meanwhile, the values in the last two columns (8th May and 7th May) in the CSV for `Total` row are `169439663` and `167346544` respectively, ***whose difference comes out to be `2093119`***. The CSV is http://api.covid19india.org/csv/latest/vaccine_doses_statewise.csv .

### Thus, there's a difference of 69587 between the MoHFW data and the CSV data.

---

Meanwhile the cowin CSV (http://api.covid19india.org/csv/latest/cowin_vaccine_data_statewise.csv) shows numbers which are more than in the earlier mentioned CSV.

For instance, the value of of `Total Doses Administered` is `167493857` under 8th May (which I suppose is 7th May data fetched on 8th May since date is under the column `Updated On`).

**Comment by ShikariShambuJr** [comment]
1) We only capture the total number of doses administered and the numbers are correct. You can verify that from the sources.We have mentioned the source along with the numbers everyday.
2)The CoWin sheet is a different sheet with a different source(dashboard.cowin.gov.in),cutoff and reporting times etc.
