### ISSUE TITLE
Better format for JSon

### ISSUE THREAD

**Issue by samewal** [covid19india/api#474]
I think json format should look like below:

[{
 "StateCode" : <StateCode>
  "delta": {
   "confirmed": <deltaConfirmedForState>",
   "deceased": <deltaDeceasedForState>",
   "recovered": <deltaRecoveredForState>",
   "vaccinated": <deltaVaccinatedForState>"
  },
  "delta7":{
     "confirmed": <7DmaConfirmedForState>",
     "deceased": <7DmaDeceasedForState>",
     "recovered": <7DmaRecoveredForState>",
     "vaccinated": <7DmaVaccinatedForState>""
  },
  "districts": [{
   "DistricName" : "District1": {
    "delta":{
     "confirmed": <deltaConfirmedForDistrict>",
     "deceased": <deltaDeceasedForDistrict>",
     "recovered": <deltaRecoveredForDistrict>",
     "vaccinated": <deltaVaccinatedForDistrict>"
    },
    "delta7":{
     "confirmed": <7DmaConfirmedForDistrict>",
     "deceased": <7DmaDeceasedForDistrict>",
     "recovered": <7DmaRecoveredForDistrict>",
     "vaccinated": <7DmaVaccinatedForDistrict>""
    },
    "meta": {
     "population": <districtPopulation>,
     "tested": {
      "last_updated": "yyyy-mm-dd",
      "source": "uri",
     },
     "notes": "notesForDistrict"
    },
    "total": {
     "confirmed": <cumulativeConfirmedNumberForDistrict>,
     "deceased": <cumulativeDeceasedNumberForDistrict>,
     "recovered": <cumulativeRecoveredNumberForDistrict>,
     "tested": <cumulativeTestedNumberForDistrict>,
     "vaccinated": <cumulativeVaccinatedNumberForDistrict>
    }
   ,
   .
   .
   .
  ],
  "meta": {
   "last_updated": "yyyy-mm-ddHH24:M:S+GMT",
   "population": <statePopulation>,
   "tested": {
    "last_updated": "yyyy-mm-dd",
    "source": "uri"
   },
   "notes": "notesForState"
  },
  "total": {
   "confirmed": <cumulativeConfirmedNumberForState>,
   "deceased": <cumulativeDeceasedNumberForState>,
   "recovered": <cumulativeRecoveredNumberForState>,
   "tested": <cumulativeConfirmedNumberForState>,
   "vaccinated": <cumulativeVaccinatedNumberForState>
  }
 },
 .
 .
 .
]

**Comment by bee-rickey** [comment]
Hi we do not plan to change the format now since this has been in use for over 6 months now.
