### ISSUE TITLE
Time series API

### ISSUE THREAD

**Issue by samewal** [covid19india/api#476]
Time series API should take date as parameter. Currently it returns data from 36 mar 2020 onwards which is huge.

**Comment by bee-rickey** [comment]
Hi we do not plan to implement anything as such as of now. Please consider doing it yourself in you do need it date specific.

**Comment by samewal** [comment]
Concern here is not ease of development. Such a heavy API which dumps whole data to user will put lot of stress on network and effect the performance. Instead if there was date specific API it will very light weight and user can make multiple calls if they want.

Solving this problem at client side will have no benefit on performance.
