### ISSUE TITLE
Test Positivity Date is Incorrectly Calculated

### ISSUE THREAD

**Issue by aatishb** [covid19india/api#479]
Hi, 

Thanks for making this amazing resource available and for your hard work maintaining it!

I believe there might be an issue with the way the test positivity rate (percentage of tests that are positive) is calculated on the site. I ran some code (pasted below) to calculate the test positivity rate from your data using the simple method of `test positivity rate = confirmed cases in past week / tests in past week`.

The values I get are generally consistent with the [MOHFW data](https://github.com/aatishb/indiatestpositivitydata), but are not consistent with the values on your site. (They are typically higher than the values you are reporting.)

>Test Positivity Rate (May 18, 7 day average)
Andhra Pradesh 24%
Arunachal Pradesh 8%
Assam 8%
Bihar 6%
Chandigarh 20%
Chhattisgarh 11%
Delhi 12%
Goa 36%
Gujarat 7%
Haryana 16%
Himachal Pradesh 26%
Jammu and Kashmir 10%
Jharkhand 7%
Karnataka 32%
Kerala 27%
Lakshadweep 13%
Madhya Pradesh 11%
Maharashtra 15%
Manipur 19%
Meghalaya 18%
Nagaland 24%
Odisha 20%
Puducherry 20%
Punjab 11%
Rajasthan 20%
Sikkim 32%
Tamil Nadu 20%
Telangana 7%
Uttar Pradesh 5%
Uttarakhand 18%
West Bengal 30%

Please let me know if I am misunderstanding something. If not, I would recommend using this method to update the test positivity numbers on your site.

Here is the code I used to generate this list.

```
# state case data https://api.covid19india.org/csv/latest/states.csv
# state testing data https://api.covid19india.org/csv/latest/statewise_tested_numbers_data.csv

import pandas as pd
from datetime import datetime, timedelta
import pytz

states = ['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli and Daman and Diu',
       'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'India',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh',
       'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry',
       'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 
       'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

cases = pd.read_csv('https://api.covid19india.org/csv/latest/states.csv')
cases.index = pd.to_datetime(cases['Date'])

tests = pd.read_csv('https://api.covid19india.org/csv/latest/statewise_tested_numbers_data.csv')
tests.index = pd.to_datetime(tests['Updated On'])

# get current date in IST
IST = pytz.timezone('Asia/Kolkata')
today = datetime.now(IST) - timedelta(days = 1)
currentdate = today.isoformat().split('T')[0]
print('Test Positivity Rate')

for state in states:
    
    statecases = cases[cases['State'] == state]['Confirmed']
    stateweeklycases = statecases - statecases.shift(7)

    statetests = tests[tests['State'] == state]['Total Tested']
    stateweeklytests = statetests - statetests.shift(7)
    
    currentstateweeklycases = stateweeklycases[stateweeklycases.index == currentdate]
    currentstateweeklytests = stateweeklytests[stateweeklytests.index == currentdate]
    if (currentstateweeklycases.size == 1 and currentstateweeklytests.size == 1):
        if (currentstateweeklycases.iloc[0] > 0 and currentstateweeklytests.iloc[0] > 0):
            print(state, str(round(100 * currentstateweeklycases.iloc[0] / currentstateweeklytests.iloc[0])) + '%')    
```

**Comment by shuklaayush** [comment]
Hey @aatishb, I'm guessing you're referring to the TPR on the table. Right now, it's calculated as Cumulative cases / Cumulative tests. It's probably a junk measure and we'll replace it with the 7-day average as you mentioned. In the meantime, you can refer to the TPR graph at the bottom for a more appropriate measure. That should match with your calculations as well

![image](https://user-images.githubusercontent.com/27727946/119397471-c7cb5b00-bcf3-11eb-9d1e-48e62b81ccdb.png)

P.S.: I loved your work on covidtrends. It was a really neat way to visualize exponentials!

**Comment by aatishb** [comment]
@shuklaayush That sounds great, just wanted to flag this in case you weren't aware of it. The 7 day average seems simpler and the numbers make more sense to me. FYI: I've also been working on a test positivity tracker using your data, as I think this metric could be helpful to more people. Will share a link when that's ready (hopefully this week). Thanks for making this data available, and also for your kind words! :)

**Comment by aatishb** [comment]
Feel free to close this issue.

BTW I'm using covid19india data to calculate test positivity here: https://aatishb.com/indiacovidtests/ Thanks again for gathering & sharing this data!
