### ISSUE TITLE
Structure's Items and descriptions should be separated by dash (-) and a new line to improve readability

### ISSUE THREAD

**Issue by A91y** [covid19india/api#480]
🔗 https://api.covid19india.org/documentation/rawdata.html

Items (e.g, currentstatus) should be separated from description (e.g, This can have: Hospitalized, Recovered, Deceased or Migrated_Others as values. These represent the status of the case. Migrated_Others is used as a place holder for those cases that are marked by states as having migrated to other states or have died due to non covid reasons.) to improved readability.

**Comment by A91y** [comment]
Please assign this issue to me. I can correct this problem.

**Comment by sudevschiz** [comment]
Didn't quite understand what is the change that you are proposing here. 
Please make an edit in this readme directly and make a PR.

https://github.com/covid19india/api/blob/master/documentation/rawdata.md

**Comment by A91y** [comment]
The PR is here. :ballot_box_with_check:
https://github.com/covid19india/api/pull/486#issue-651409032

**Comment by A91y** [comment]
The Issue is solved with PR merge.
