### ISSUE TITLE
Huge data different

### ISSUE THREAD

**Issue by dlinx** [covid19india/api#483]
I found the huge difference between official numbers and the app.
District: Nanded Maharashtra
Total cases by website: approx 3k
Total cases by govt official document: approx 2k

Reference: 
![SAVE_20210522_152923](https://user-images.githubusercontent.com/5583697/119217200-8ed49000-bb13-11eb-8247-44a13ed3c38d.jpg)

**Comment by sudevschiz** [comment]
Hi,

We use MH state bulletin to add the cases and not individual district
bulletins.
