### ISSUE TITLE
Time in the dayt when data is updated

### ISSUE THREAD

**Issue by pkattuman** [covid19india/api#484]
Thanks very much for your valuable work. It is much appreciated.

It would be useful to know what time in the evening the daily time series data is updated. 
This helps to start from analysis in a timely way

Best wishes

**Comment by sudevschiz** [comment]
Daily time series data is updated between 11:30 PM to 00:30AM IST. There is an automated script that triggers this update.
Rarely, the script might not run and the data might not get updated, but we try to add it by end of next day.

**Comment by pkattuman** [comment]
Thanks very much indeed for this, and you’re your valuable work on compiling this data.

Please see this example of the (weekly updated) output produced from the data.
https://www.jbs.cam.ac.uk/covid-india

Please feel free to share with those who may be interested in seeing these forecasts. They  are updated every Monday 10 am BST

Best wishes
Paul Kattuman

-------------------------------
Dr. Paul Kattuman
Judge Business School
University of Cambridge
