### ISSUE TITLE
Vaccine Data May 20....something is off!

### ISSUE THREAD

**Issue by KK712** [covid19india/api#485]
Hi

There is an astronomical jump in total vaccines administered between May 19 and May 20 (around 49 lakhs), although the cumulative number seems to add up as of date.  The 49 lakh number does not match any government source and is almost impossible to believe. Was there some sort of correction?

Best

**Comment by KK712** [comment]
This is for the file "vaccine_doses_statewise".

**Comment by ShikariShambuJr** [comment]
Check (https://twitter.com/covid19indiaorg/status/1395696973185896448?s=20)
