### ISSUE TITLE
Incorrect number of tests at the country level

### ISSUE THREAD

**Issue by jishnub** [covid19india/api#491]
The total tests carried out yesterday (1 June) shows up as 32.7L on the website. However this does not match the numbers reported by ICMR: [20L tested on 1st June](https://www.icmr.gov.in/pdf/covid/update/ICMR_testing_update_02Jun2021.pdf)

**Comment by ShikariShambuJr** [comment]
There is  reconciliation which i written clearly there in the doc you mentioned.

**Comment by jishnub** [comment]
The reconciliation is in the total tested number and not the daily tests. That's an oddly confrontational tone to take.

**Comment by ShikariShambuJr** [comment]
In case you thought that the tone was confrontational tone I would like to apologize. We calculate the daily numbers by subracting the cumulative numbers.

**Comment by jishnub** [comment]
OK thanks, that makes sense. It's a shame that the numbers are so different

**Comment by ShikariShambuJr** [comment]
Yes agree with that. They should release Time Series Data so that we could add these numbers in retrospect preventing this artificial surge.
