### ISSUE TITLE
"States.csv" || Issue with India level daily Tests

### ISSUE THREAD

**Issue by arunavachatterjee** [covid19india/api#495]
Issue with "states.csv" [https://api.covid19india.org/csv/latest/states.csv]

The number of **Tests per day** - total of States vs India - don't add up.

Especially from **June 1**, there's a huge difference showing between total no. of tests (India) vs total no. of Tests of all States put together (per day basis).

See screenshots attached as well as ICMR daily Tests (national) screenshot as of June 05.
![Screenshot 2021-06-06 235942](https://user-images.githubusercontent.com/7095253/120936032-5c39b280-c723-11eb-9d7b-4a0fb3359612.jpg)
![Screenshot 2021-06-06 235247](https://user-images.githubusercontent.com/7095253/120936037-5e037600-c723-11eb-9371-5327bea86049.jpg)
![Screenshot 2021-06-06 235749](https://user-images.githubusercontent.com/7095253/120936038-5e037600-c723-11eb-8687-e59277ca4ef8.jpg)

**Comment by sudevschiz** [comment]
Hi,
The state level testing data is captured from the state bulletins and the nation-level testing data is from the number published by ICMR. There could be lags or leads between these two numbers. Hence the difference.
