### ISSUE TITLE
Invalid district "Vellorer" in Tamilnadu

### ISSUE THREAD

**Issue by worldofprasanna** [covid19india/api#50]
Duplicate entry for the district "Vellore" is present and the name is given as Vellorer.

@JunaidBabu - From your previous comment, saw that the corresponding google sheet has to be corrected by removing this data. Thanks.

File: state_district_wise.json, Line: 508

**Comment by JunaidBabu** [comment]
https://github.com/covid19india/api/issues/51#issuecomment-607166974
