### ISSUE TITLE
Dates in vaccination data sheet have 2 formats

### ISSUE THREAD

**Issue by HarikrishnaSrirangam** [covid19india/api#503]
You have both 16/01/2021 (mm/dd/yyyy) mixed with 1/2/2021 like dates. Please make it all mm/dd/yyyy or dd/mm/yyyy. Thanks.

**Comment by ShikariShambuJr** [comment]
Which sheet are you referring to?

**Comment by HarikrishnaSrirangam** [comment]
> Which sheet are you referring to?

vaccine_doses_statewise_v2.csv - I did a download from your API site. See the difference in the first rows till row 571 and then thereon. I am unable to upload my downloaded file here.

**Comment by HarikrishnaSrirangam** [comment]
> > Which sheet are you referring to?
> 
> vaccine_doses_statewise_v2.csv - I did a download from your API site. See the difference in the first rows till row 571 and then thereon. I am unable to upload my downloaded file here.

31/01/2021 | Miscellaneous | 52120 | 0 | 52120
31/01/2021 | Total | 3758843 | 0 | 3758843
1/2/2021 | Andaman and Nicobar Islands | 2727 | 0 | 2727

**Comment by ShikariShambuJr** [comment]
Works fine on our end. Can you check on your side?
![Screenshot from 2021-07-06 12-07-27](https://user-images.githubusercontent.com/68983486/124554484-a5c90a80-de53-11eb-9f7a-c0d66c24d442.png)

**Comment by HarikrishnaSrirangam** [comment]
> Works fine on our end. Can you check on your side?
> ![Screenshot from 2021-07-06 12-07-27](https://user-images.githubusercontent.com/68983486/124554484-a5c90a80-de53-11eb-9f7a-c0d66c24d442.png)

Seems like Excel is messing up something. Let me figure out. Thanks and sorry for the bother.

**Comment by HarikrishnaSrirangam** [comment]
Looks like a problem exporting csv into Excel. Dump looks ok.
