### ISSUE TITLE
Gujarat District wrong names in API but in the map it shows correct name

### ISSUE THREAD

**Issue by circuitmamu** [covid19india/api#51]
https://api.covid19india.org/state_district_wise.json
To verify official names visit official guj govt site for COVID-19
https://gujcovid19.gujarat.gov.in/

~~Ahmadabad~~ => **Ahmedabad**
~~Mahesana~~ => **Mehsana**
~~Kachchh~~ => **Kutch**

Please rectify it and if need any help I can help it for Gujarat state data

**Comment by circuitmamu** [comment]
#41 is same case of typos in Gujarat cities

**Comment by JunaidBabu** [comment]
Most of these issues are fixed. If it's still happening, please report at https://github.com/covid19india/covid19india-react
