### ISSUE TITLE
Day wise district data not found

### ISSUE THREAD

**Issue by yogesh7401** [covid19india/api#510]
I got day wise district data from (https://api.covid19india.org/v4/min/data-all.min.json) end point
But after the recent update that end point is removed.
where I can get day wise data for districts ?

**Comment by bee-rickey** [comment]
Please refer to the readme. The location has changed to data.covid19india.org

**Comment by yogesh7401** [comment]
[https://data.covid19india.org/v4/min/data-all.min.json](https://data.covid19india.org/v4/min/data-all.min.json) Showing 404 Page not found
