### ISSUE TITLE
Count of patients with deceased not matching with the dashboard numbers 

### ISSUE THREAD

**Issue by vikpy** [covid19india/api#53]
Checked the status attribute and took a count of patients with status as deceased in Maharashtra. It is 10 on the dashboard 

API used:
https://api.covid19india.org/raw_data.json

**Comment by kirpal06391** [comment]
+1

**Comment by sanilborkar** [comment]
So I ran a script to pull all statuses from https://api.covid19india.org/raw_data.json and this is what I got

```
Data Length = 1599

Statuses: {'', 'Hospitalized', 'Deceased', 'Recovered', 'Migrated'}

Confirmed: 1442
Migrated: 1
Active: 1366
Recovered: 54
Deceased: 21
```

Are we missing something?

**Comment by aekanshd** [comment]
#45 Similar problem.

**Comment by amit-arora01** [comment]
Issue is not with API but the data compilation itself. raw sheet has the same numbers, seems like website is picking up data from some other source

**Comment by krishnasen2401** [comment]
its picking up form data.json api

**Comment by JunaidBabu** [comment]
This is something we're finding difficult time right now.. When there are reports on deceased or recovered, we are not able to map it to the patient ID for most cases. So we are tracking them in a separate sheet as of now.

**Comment by vikpy** [comment]
I need data for state/union territory-wise time series forecasting. Is it possible to get the data from 30-01-2020 till the current date for each state and union territory? Or is there a source using which I can generate such a state-wise time series data?

**Comment by amit-arora01** [comment]
> This is something we're finding difficult time right now.. When there are reports on deceased or recovered, we are not able to map it to the patient ID for most cases. So we are tracking them in a separate sheet as of now.

@JunaidBabu can we publish the data on sheet deaths_and_recovered in a seperate API?

**Comment by sudevschiz** [comment]
@amit-arora01 https://github.com/covid19india/api/issues/65
