### ISSUE TITLE
Consider giving the dataset to Kaggle

### ISSUE THREAD

**Issue by amsaha** [covid19india/api#59]
https://www.kaggle.com/datasets

**Comment by sudevschiz** [comment]
User SRK had already added our data in his dataset. https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset

Hope you'll support by publishing the API further. :)

**Comment by arnabbiswas1** [comment]
From SRK's dataset I have ended up here. I noticed that in the above mentioned dataset district wise vaccination data is not available. I have posted a topic there requesting him to include those data points as well.

https://www.kaggle.com/sudalairajkumar/covid19-in-india/discussion/248016

**Comment by arnabbiswas1** [comment]
I have created a kaggle dataset with district wise vaccination data here:

https://www.kaggle.com/arnabbiswas1/covid-vaccination-india-district-wise-data/
