### ISSUE TITLE
Data mismatch with regarding statesv2

### ISSUE THREAD

**Issue by krishnasen2401** [covid19india/api#60]
Data in main statesv2 api is different than that of maindashboard a new values of unknown states is getting processed including the unknown districts compared with data.json,raw_data for cities and statesv2 for daily deltas of districts 

![image](https://user-images.githubusercontent.com/13378434/78210809-e99ec880-74c8-11ea-8b7b-61a907c86214.png)

even when using single table same result while processing the api

![image](https://user-images.githubusercontent.com/13378434/78211190-e821d000-74c9-11ea-8ee0-01d8cea36b96.png)

in api url also same representation

![image](https://user-images.githubusercontent.com/13378434/78211380-667e7200-74ca-11ea-9391-e7cfc95a1961.png)

**Comment by sudevschiz** [comment]
Can you confirm if this is still an issue? Since the backend data is being edited constantly, there could be a point in time when some state was mentioned as Unknown. 
Please do check again and report

**Comment by krishnasen2401** [comment]
Yes it's still a issue in api but I am filtering it out

![15859090081952352685277295365408](https://user-images.githubusercontent.com/13378434/78350162-58ac1800-75c2-11ea-8e73-7d33a5c62bee.jpg)

**Comment by sudevschiz** [comment]
@JunaidBabu could you have a look? How's `v2/state_district_wise.json` prepared?

**Comment by JunaidBabu** [comment]
This happens because in the sheets there are extra rows with only patient ID and other fields blank. Need to filter those in the api. I'll work on a fix

**Comment by JunaidBabu** [comment]
Removed unknown states from the json 1b912b3a814d66c65f187fde26424bd8fca3faa8
