### ISSUE TITLE
Link to latest update source from each state 

### ISSUE THREAD

**Issue by kousiksatish** [covid19india/api#63]
This issue is linked to https://github.com/covid19india/covid19india-react/issues/558

**Is your feature request related to a problem? Please describe.**
No. It is a new feature which would help people like me who would like to know more about the update.

**Describe the solution you'd like**
In recent days, we see that each state government is mostly giving one update per day. It would be good if we could the link to the source of this update.

**Comment by kousiksatish** [comment]
@JunaidBabu Please assign it to me, if you find this enhancement acceptable. I would like to work on it.

**Comment by sudevschiz** [comment]
Making the API more useful is always welcome. Please do share the structure in which you want to provide this link. Many a times, there are multiple source links.

Anyway, assigning to you.

**Comment by kousiksatish** [comment]
@sudevschiz I will review and get back to you.

**Comment by kousiksatish** [comment]
@sudevschiz I wish to add it in the data.json -> statewise -> latestSources as shown below:
![Screen Shot 2020-04-04 at 12 23 08 PM](https://user-images.githubusercontent.com/6641694/78420707-2f959100-766f-11ea-97ab-735cedd0df17.png)

I wish to know how to add it in there. As far as I understood from the code, it is directly fetched from the excel sheet. 

Should we change add this column in excel sheet or make code changes.

If it is code, please point me to the js file corresponding to it.

**Comment by kousiksatish** [comment]
@sudevschiz @JunaidBabu Please provide your inputs so that we can get this done. I am struck here

**Comment by sudevschiz** [comment]
There are several considerations here:
1. For the confirmed cases, the source has to be fetched from the raw_data.json. That too, cases are now bulk updated. So 20-30 cases might have the same source. Please have a look at the sheet to understand further.
2. Deaths and Recovered has to be fetched from a different sheet. Not sure if that is being made into an API already @JunaidBabu ?


From these data, might have to implement some logic to add these sources to the corresponding State and corresponding confirmed/recovery/deceased

Also, another consideration is that this json is used serving the main webpage and the size of this json should be as small and sufficient as possible. 

What do you think?

**Comment by kousiksatish** [comment]
Agree that the size should be small, we will be adding latest sources for today. Max 2 links

**Comment by kousiksatish** [comment]
As you mentioned, fetching it from raw data, looks slightly complicated but not impossible... Is there any other way you could think of? I will review and get back with more info.

**Comment by sudevschiz** [comment]
@shuklaayush Should this be added using the new parser?

**Comment by shuklaayush** [comment]
I don't see the utility of adding it to the parser, unless we add it to the website as well. The parser should only contain info that is displayed somewhere on the website.
