### ISSUE TITLE
Add Death_And_Recovery sheet as an API

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/api#65]
Currently, details in the raw_data for death and recovery won't match the exact numbers because, most of the time we won't have the exact details which patient the news or bulletin is referring to.

So, we have created a separate sheet where this details are added. 

It would be great if this sheet is provided as an API separately or as part of raw_data.

**Comment by faisal3389** [comment]
let me know if this enhancement is accepted, I would like to contribute to this API

**Comment by avneeshroks** [comment]
Was trying for this API, what's the sheet id for Death_And_Recovery tab? Or where to find the Sheet Id's for the tabs in https://docs.google.com/spreadsheets/d/e/2PACX-1vSc_2y5N0I67wDU38DjDh35IZSIS30rQf7_NYZhtYYGU1jJYT6_kDx4YpF-qw0LSlGsBYP8pqM_a1Pd/pubhtml#

**Comment by sudevschiz** [comment]
@JunaidBabu Can @faisal3389 work on this?

**Comment by JunaidBabu** [comment]
d7c466a7f241738b54301e452519ac4f1e43e5c3
