### ISSUE TITLE
additional attribute in national time series

### ISSUE THREAD

**Issue by subratray** [covid19india/api#70]
The wrapper "cases_time_series" has an attribute named as date in national time series API  (https://api.covid19india.org/data.json). _date_ is a reserved key word in many systems. To allow them to parse this data, please add another attribute to return the same data as _data_ attribute.

{
			"...
			"dailyrecovered": "0",
			"date": "30 January ",
			"...
		}

**Comment by sudevschiz** [comment]
It's a JSON object. `date` is quite valid, I would say. Please handle this at the consumer end,
