### ISSUE TITLE
API (lost key_values Array)

### ISSUE THREAD

**Issue by abhikhaiwale** [covid19india/api#72]
https://api.covid19india.org/data.json 
Api has lost the key_values array. It is not showing that anymore.
Please fix it.

**Comment by asprazz** [comment]
Yeah! I noticed it too, but it was removed in 4162f334e1ee3ba7af201199070f9ef77163bb8f may be by keeping something in mind..

**Comment by prakharbhardwaj** [comment]
I guess Key_value array is no more needed as delta values are now declared in [statewise] -> {state: Total}

**Comment by abhikhaiwale** [comment]
> 
> 
> I guess Key_value array is no more needed as delta values are now declared in [statewise] -> {state: Total}

Thanks for the information. Really helped.

**Comment by ishan0445** [comment]
Hi,
Even my telegram bot just broke due to this update in APIs, 
It is suggested that the JAON structure should not be modified since there can be a lot of apps that are dependent on it and they all will break.
All the new changes should be made in the v2 APIs or higher

**Comment by krishnasen2401** [comment]
@JunaidBabu did the api  fail or was it removed???

**Comment by JunaidBabu** [comment]
`key_value` field was a copy of the data in `statewise[0]`. We're sorry for removing this field abruptly, had to do some hard refactoring in the sheets.. All the data is still available in data.json itself in the total field. Could you please use them?

**Comment by krishnasen2401** [comment]
Thank for the clarification will definitely do so
