### ISSUE TITLE
API shows Gujarat as a district inside Maharashtra

### ISSUE THREAD

**Issue by kavishdahekar** [covid19india/api#75]
Replicating this issue from [covid19india-react#718](https://github.com/covid19india/covid19india-react/issues/718)

Gujarat is displayed as a state in Maharashtra.

Lines of code:
https://github.com/covid19india/api/blob/548ae6e3fc5020fa931b271f02fe4f7523f256bc/state_district_wise.json#L1297

https://github.com/covid19india/api/blob/548ae6e3fc5020fa931b271f02fe4f7523f256bc/v2/state_district_wise.json#L1488

**Comment by amit27592** [comment]
Maybe those are originally Gujarat patients who have since been moved to Mumbai. (Like foreign nationals who were moved to the embassy). Not sre how those are populated in the API.

It would be helpful in getting clarity here.

**Comment by kavishdahekar** [comment]
Yeah that could be the case, but it leads to "Gujarat*" showing up as a district under Maharashtra which could be misleading.

Do we have the code that pulls data from the crowd sourced sheet and updates the api?

**Comment by amit27592** [comment]
The code is also in the repository. It is technically a node module with package.json missing.

You can clone the repo, install required packages (see package-lock.json for dependencies), and run the js scripts.

I think to get started, view pushthejson file (Shell script).

**Comment by kavishdahekar** [comment]
Thank you @amit27592 , will try that out!

**Comment by sudevschiz** [comment]
Gujarat* was intentionally kept in the district list. Others have also raised this confusion. We will work on this.

**Comment by Arusara** [comment]
can i take this work item @sudevschiz ?

**Comment by sudevschiz** [comment]
There is no change to be done in the code base. This has to be edited in the Google sheet itself.

However, we'll continue to mark them this way for lack of better way to match with how the state reports consider these cases

**Comment by kavishdahekar** [comment]
Thanks for the update. Closing this issue.
