### ISSUE TITLE
Problem with /v2/state_district_wise.json

### ISSUE THREAD

**Issue by ifrahur** [covid19india/api#76]
Can the format of [state_district_wise](https://api.covid19india.org/v2/state_district_wise.json) be changed to the format same as in [statewise](https://api.covid19india.org/data.json) to make it simpler to parse it easily in a dynamic manner.

**Current Format**
> [
  {
    "state": "Kerala",
    "districtData": [
      {
        "district": "Thrissur",
        "confirmed": 12,
        "lastupdatedtime": "",
        "delta": {
          "confirmed": 0
        }
      },
      {
        "district": "Alappuzha",
        "confirmed": 3,
        "lastupdatedtime": "",
        "delta": {
          "confirmed": 0
        }
      },

**proposed format** 

> {
    "state": "Kerala",
    "districtData": [
      {
        "district": "Thrissur",
        "confirmed": 12,
        "lastupdatedtime": "",
        "delta": {
          "confirmed": 0
        }
      },
      {
        "district": "Alappuzha",
        "confirmed": 3,
        "lastupdatedtime": "",
        "delta": {
          "confirmed": 0
        }
      },
      {
        "district": "Kasaragod",
        "confirmed": 143,
        "lastupdatedtime": "",
        "delta": {
          "confirmed": 0
        }
      },

**Comment by JunaidBabu** [comment]
What's the difference between current and proposed formats? 🤔

**Comment by ifrahur** [comment]
> What's the difference between current and proposed formats? 🤔

i'm sorry this format..

`{
	"districtWise": [
		{
			"state": "Maharashtra",
			"districtData": [
				{
					"districtName": "Pune",
					"confirmed": 42,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 5
					}
				},
				{
					"districtName": "Mumbai",
					"confirmed": 75,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 3
					}
				}
			]
		},
		{
			"state": "Kerala",
			"districtData": [
				{
					"districtName": "Thrissur",
					"confirmed": 7,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 0
					}
				},
				{
					"districtName": "Alappuzha",
					"confirmed": 2,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 0
					}
				}
			]
		},
		{
			"state": "Unknown",
			"districtData": [
				{
					"districtName": "Unknown",
					"confirmed": 284,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 0
					}
				}
			]
		}
	]
}`
