### ISSUE TITLE
updating the /v2/state_district_wise.json format

### ISSUE THREAD

**Issue by shishir-gangwar** [covid19india/api#78]
Can we use the following json format :- 
{
  "Kerala": {
      "districtData": {
         "Thrissur": {
            "confirmed": 12,
            "active": 10,   // new addition
            "deaths": 0,  // new addition
            "recovered": 2,  // new addition
            "lastupdatedtime": "",
            "delta": {
                "confirmed": 0,
                "active": 0,  // new addition
                "deaths": 0, // new addition
               "recovered": 0 // new addition
             }
      }
}
This can help us track the number of active and recovered cases per city. We can display this info on the website.

**Comment by ifrahur** [comment]
yes please.. 
even i mentioned the same in problem #76 
it'll be easier for people to work with it..
