### ISSUE TITLE
states_daily.json does not have previous day's data ...

### ISSUE THREAD

**Issue by Sdaas** [covid19india/api#79]
https://api.covid19india.org/states_daily.json / states_daily.json file does not seem to have the most recent data. Right now ( Apr 6th ), this seems to have data only till Apr 4th. How frequently is this supposed to be updated ?

**Comment by onclave** [comment]
I'm facing the same issue. Why is this not being updated even though the commit message says it has been updated for both 5th and 6th April data?

**Comment by amit27592** [comment]
Seems to be fixed now.

**Comment by onclave** [comment]
Yes, it has been fixed. @Sdaas this issue can be closed now.
