### ISSUE TITLE
Automated code review for Covid-19 monitor API

### ISSUE THREAD

**Issue by P-ignatovich** [covid19india/api#80]
Hi!
I am a member of the team developing **monocodus** — a service that performs automatic code review of GitHub pull requests to help organizations ensure a high quality of code.
We’ve developed some useful features to the moment, and now we’re looking for early users and feedback to find out what we should improve and which features the community needs the most.

We ran monocodus on a pre-created fork of your repo on GitHub https://github.com/monocodus-demonstrations/api/pulls, and it found some issues related to the usage of increment. I hope that this information will be useful to you and would be happy to receive any feedback here or on my email pavel@monocodus.com.
If you want to try our service, feel free to follow the link: https://www.monocodus.com
The service is entirely free of charge for open source projects. 

We appreciate the hard work you're doing during difficult times of the world pandemic which we hope will be over soon.

**Comment by JunaidBabu** [comment]
If you've found issues, could you raise a PR with the fix?
