### ISSUE TITLE
New field in the data.json

### ISSUE THREAD

**Issue by TheDominus** [covid19india/api#82]
Requirements - 
In the case time series part of the data.json, we have confirmed, deceased and recovered data but if we can have **active cases** also i.e.```confirmed - deceased - recovered```. It can be useful to create many graphs and will decrease the redundant calculations.

Analysis required - 
However, more analysis needs to be done if we should contain redundant data in API to ease of graph formation or should be calculated on the go.

**Comment by TheDominus** [comment]
@JunaidBabu

**Comment by JunaidBabu** [comment]
Thanks for the input. But it seems redundant. This can be done on client side itself.
