### ISSUE TITLE
lastupdatedtime:  is correct last updated time ?

### ISSUE THREAD

**Issue by rashnk** [covid19india/api#83]
In the data.json endpoint lastupdatedtime is not correct date
confirmed and deltaconfirmed are correct number and  uptodate  for 07-04-2020 9:00 for Kerala, but the api return last updatedtime as lastupdatedtime: "06/04/2020 19:24:25"

**Comment by JunaidBabu** [comment]
@sudevschiz

**Comment by sudevschiz** [comment]
Seems okay now.
Google Scripts were timing out during the day a few times due to some network error reason. Could be due to that?
