### ISSUE TITLE
Telangana data is not updated, too many 'Unknowns' in state_district_wise

### ISSUE THREAD

**Issue by data-domain** [covid19india/api#88]
Currently for Telangana it shows 104 for Hyderabad and 277 for Unknown district.

But Telangana data  from government [here ](https://covid19.telangana.gov.in/wp-content/uploads/2020/04/Telangana-Health-Department-Media-bulletin-08-04-2020.pdf) gives clear numbers for all districts (no Unknowns). Hyderabad is 161 now.

Please consider updating, thank you!

**Comment by sudevschiz** [comment]
We did notice the district wise list from Telangana government. However we are struggling to map the exact patient to each district. Working on this.

**Comment by sudevschiz** [comment]
This has been fixed as much as possible with the hardwork of the volunteers. There are still Unknowns remaining, that's because we simply don't have the data to map them correctly. 

We will continue looking for it.
