### ISSUE TITLE
Feature Request: Add the ability to query raw data by date

### ISSUE THREAD

**Issue by abishekrsrikaanth** [covid19india/api#90]
Can you add the ability to query the raw data by the date on which the data was added? Processing all the data in one go is quite a time consuming job

**Comment by JunaidBabu** [comment]
This is one issue we are struggling with right now. Since the size of raw_data is becoming bigger every day, we might need to find alternate ways. Maybe breakdown the json file into different files based on date or state for example.

Do you have any suggestions?

**Comment by bauripalash** [comment]
Directly using the `raw_data.json` file in the webapp is not a good idea. We could just split it according to our needs, for example in the deepdive feature instead of calculating the gender values, age distribution etc. on client side , the task can be done here creating a new json with calculated values.

**Comment by abishekrsrikaanth** [comment]
I don't really see a point in breaking down the `raw_data.json` file because the whole file tells a story. Breaking them wouldn't do the same. 

Right now, what I am doing is retrieving the raw data every hour and importing it into an elastic search server to make the queries as required within my app. The problem that I currently have is 2 folds:

- I don't have a way to see which record was recently updated.
- I don't have a way to know if the `raw_data.json` has any changes from the last time I retrieved it.

The reason why asked to have the json file queryable is because I can retrieve only the data that has changed which is why I raised another issue request #91

**Comment by sudevschiz** [comment]
This could be achieved by keeping a daily snapshot of the data, organized in folders? I guess this can be saved as a separate workflow. This would solve #116 too, I guess

**Comment by siddharthjaidka** [comment]
can we build an API server with all these query needs on top of the data layer? a minor structure change can provide only the essential data for the web app with minimum overhead and those who want full details can get it with a separate endpoint?

**Comment by JunaidBabu** [comment]
An experimental setup is available here. Please share your inputs about the format and other requirements


https://github.com/covid19india/api/tree/gh-pages/cases

examples:
https://api.covid19india.org/cases/state/
https://api.covid19india.org/cases/state/KL/

https://api.covid19india.org/cases/date/
https://api.covid19india.org/cases/date/20-04-2020/

**Comment by ret394** [comment]
names of folders in https://github.com/covid19india/api/tree/gh-pages/cases/date a/c to ISO 8601
and use 24 hour clock for recording time, would help with parsing. keep it orthogonal to convention of popular libraries, to allow easy , hassle-free use.

and use `Apr 23 2020` like format for display to humans/ users.

thanks. have a nice day. keep up the good work.

[ret394](https://github.com/ret394)

**Comment by sopanlavhale** [comment]
> I don't really see a point in breaking down the `raw_data.json` file because the whole file tells a story. Breaking them wouldn't do the same.
> 
> Right now, what I am doing is retrieving the raw data every hour and importing it into an elastic search server to make the queries as required within my app. The problem that I currently have is 2 folds:
> 
> * I don't have a way to see which record was recently updated.
> * I don't have a way to know if the `raw_data.json` has any changes from the last time I retrieved it.
> 
> The reason why asked to have the json file queryable is because I can retrieve only the data that has changed which is why I raised another issue request #91

we can use startTime and endTime and updateDate? it is good for me if I am contributing to this project.

**Comment by JunaidBabu** [comment]
Adding `on hold` until raw_data v1, v2, v3 are merged.

**Comment by feast0101** [comment]
Hi, I have created a search engine based on your APIs indexing daily covid-19 related data.
Please refer to issue: https://github.com/covid19india/api/issues/390

For demo purpose, I have deployed the search engine on Google Cloud:
**Ex: Query for raw data entered on 22nd July:**
https://covidservice-axuikumjgq-uc.a.run.app/solr/covid19/select?fq=dateannounced%3A%2222%2F07%2F2020%22&q=*%3A*

**Comment by JunaidBabu** [comment]
This is available in v4 end points now.
