### ISSUE TITLE
Feature Request: Add Last update time to raw data json

### ISSUE THREAD

**Issue by abishekrsrikaanth** [covid19india/api#91]
Can you please add a global `last_updated_time` field to the `raw_data.json` so we would know if we require the data needs to be processed or not.

**Comment by sudevschiz** [comment]
@JunaidBabu I believe this has to be done at the API end. Just add a key-value to the json IF there is a valid diff? 

This is if there last updated time in raw_data.json should be for updated for ANY change: adding a patient detail or adding a new source link in a previous case.

If the last updated time should be the time when a confirmed case is added or recovery is reported, we can use the last updated time in the Statewise sheet.


But I think OP's objective is to get the former.
