### ISSUE TITLE
Minor typo in the banner

### ISSUE THREAD

**Issue by pyarisinghk** [covid19india/api#93]
The banner showed a minor typo. "grociery" was used in the banner. (id: 16) instead of "grocery". Tried editing the Patient Database excel. However, could not do it and hence listing it here as an issue.

**Comment by pyarisinghk** [comment]
Also, on the banner id 12 - there can be a space after "Be considerate" and before "Help those in need"

**Comment by Nitin96Bisht** [comment]
@pyarisinghk You can't access the sheet until you have owner access. You can request for owner access.

**Comment by sudevschiz** [comment]
Fixed this. Thank you.
