### ISSUE TITLE
Using Apache Kafka Streams for delta and daily calculations

### ISSUE THREAD

**Issue by xsreality** [covid19india/api#95]
Hi,

I have built an event streaming architecture with Apache Kafka that reads the raw_data.json and data.json APIs to calculate the delta changes (shown as updates on the website) and daily increments. Currently I am using to send updates via a Telegram bot to any subscribers. The updates are similar to what gets sent in Instant updates channel in Telegram.

The Apache Kafka streams code and design is available here: https://github.com/xsreality/covid19

Just wanted to let you know if this setup is useful for you in any way or if you need help with Apache Kafka, let me know!

Keep up the good work :)

**Comment by sudevschiz** [comment]
Thanks a lot for using the API. Will update your project to the README :)
